const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>new Intl.NumberFormat('ar-SD',{maximumFractionDigits:0}).format(Number(n||0));
const api=async(path,opt={})=>{const r=await fetch(path,{headers:{'Content-Type':'application/json'},credentials:'same-origin',...opt});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'حدث خطأ');return j};
$('#menu').onclick=()=>$('#nav').classList.toggle('open');
async function loadPublic(){const x=await api('/api/public/summary');$('#sProjects').textContent=fmt(x.projects);$('#sBeneficiaries').textContent=fmt(x.beneficiaries);$('#sVolunteers').textContent=fmt(x.volunteers);$('#sDonations').textContent=fmt(x.donations);$('#projectCards').innerHTML=x.featured.length?x.featured.map(p=>`<article class="card"><span class="status">${p.status}</span><h3>${p.name}</h3><p>${p.summary||'مشروع تنموي ضمن برامج بُنْيَان.'}</p><small>الإنجاز ${p.progress||0}%</small><div class="progress"><i style="width:${Math.max(0,Math.min(100,p.progress||0))}%"></i></div></article>`).join(''):'<p>ستُعلن المشروعات قريبًا.</p>'}
loadPublic().catch(console.error);
const overlay=$('#overlay'), admin=$('#admin'); $('#adminBtn').onclick=()=>overlay.classList.add('show');$('#closeLogin').onclick=()=>overlay.classList.remove('show');
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.target));try{await api('/api/login',{method:'POST',body:JSON.stringify(f)});overlay.classList.remove('show');openAdmin()}catch(err){$('#loginError').textContent=err.message}};
async function openAdmin(){admin.classList.add('show');await showView('dashboard')} $('#exitAdmin').onclick=()=>admin.classList.remove('show');
$('#logoutBtn').onclick=async()=>{await api('/api/logout',{method:'POST'});admin.classList.remove('show')};
$('#backupBtn').onclick=()=>location.href='/api/backup';
$$('.admin aside button[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));
const defs={projects:{title:'المشروعات',cols:[['name','المشروع'],['status','الحالة'],['budget','الميزانية'],['spent','المنصرف'],['progress','الإنجاز %']],fields:[['name','اسم المشروع','text'],['summary','الملخص','textarea'],['status','الحالة','select','مخطط|قيد التنفيذ|متوقف|مكتمل'],['budget','الميزانية','number'],['spent','المنصرف','number'],['progress','الإنجاز %','number'],['start_date','البداية','date'],['end_date','النهاية','date']]},beneficiaries:{title:'المستفيدون',cols:[['full_name','الاسم'],['phone','الهاتف'],['service','الخدمة'],['status','الحالة']],fields:[['full_name','الاسم الكامل','text'],['phone','الهاتف','text'],['service','الخدمة','text'],['status','الحالة','select','نشط|مكتمل|موقوف'],['notes','ملاحظات','textarea']]},volunteers:{title:'المتطوعون',cols:[['full_name','الاسم'],['phone','الهاتف'],['skill','المهارة'],['hours','الساعات'],['status','الحالة']],fields:[['full_name','الاسم الكامل','text'],['phone','الهاتف','text'],['skill','المهارة','text'],['hours','الساعات','number'],['status','الحالة','select','نشط|غير نشط']]},donations:{title:'التبرعات',cols:[['donor','المتبرع'],['amount','المبلغ'],['currency','العملة'],['donation_type','النوع'],['payment_method','الدفع']],fields:[['donor','المتبرع','text'],['amount','المبلغ','number'],['currency','العملة','select','SDG|SAR|USD'],['donation_type','النوع','select','غير مقيد|مقيد'],['payment_method','وسيلة الدفع','text']]}};
async function showView(view){$$('.admin aside button[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='dashboard')return dashboard();const d=defs[view], rows=await api('/api/'+view);$('#adminTitle').textContent=d.title;$('#adminContent').innerHTML=`<div class="toolbar"><button onclick="openForm('${view}')">إضافة سجل</button><span>${rows.length} سجل</span></div><div class="tablewrap"><table class="datatable"><thead><tr>${d.cols.map(c=>`<th>${c[1]}</th>`).join('')}<th>إجراء</th></tr></thead><tbody>${rows.map(r=>`<tr>${d.cols.map(c=>`<td>${['amount','budget','spent'].includes(c[0])?fmt(r[c[0]]):r[c[0]]??''}</td>`).join('')}<td><button class="danger" onclick="removeRow('${view}',${r.id})">حذف</button></td></tr>`).join('')}</tbody></table></div>`}
async function dashboard(){const x=await api('/api/dashboard');$('#adminTitle').textContent='لوحة القيادة';$('#adminContent').innerHTML=`<div class="kpis"><div class="kpi">المشروعات<strong>${fmt(x.projects)}</strong></div><div class="kpi">المستفيدون<strong>${fmt(x.beneficiaries)}</strong></div><div class="kpi">المتطوعون<strong>${fmt(x.volunteers)}</strong></div><div class="kpi">التبرعات<strong>${fmt(x.donations)} ج.س</strong></div><div class="kpi">ميزانيات المشروعات<strong>${fmt(x.budget)} ج.س</strong></div><div class="kpi">المنصرف<strong>${fmt(x.spent)} ج.س</strong></div></div>`}
window.openForm=type=>{const d=defs[type];const html=d.fields.map(([k,l,t,opts])=>`<label class="${t==='textarea'?'full':''}">${l}${t==='select'?`<select name="${k}">${opts.split('|').map(v=>`<option>${v}</option>`).join('')}</select>`:t==='textarea'?`<textarea name="${k}" rows="3"></textarea>`:`<input name="${k}" type="${t}" ${['name','full_name','donor','amount'].includes(k)?'required':''}>`}</label>`).join('');document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="recordModal"><form class="modalbox" id="recordForm"><h2>إضافة — ${d.title}</h2><div class="modalgrid">${html}</div><div class="actions"><button class="gold">حفظ</button><button type="button" onclick="recordModal.remove()">إلغاء</button></div></form></div>`);$('#recordForm').onsubmit=async e=>{e.preventDefault();const o=Object.fromEntries(new FormData(e.target));['amount','budget','spent','progress','hours','project_id'].forEach(k=>{if(o[k]!=='')o[k]=Number(o[k])});try{await api('/api/'+type,{method:'POST',body:JSON.stringify(o)});$('#recordModal').remove();showView(type);loadPublic()}catch(err){alert(err.message)}}};
window.removeRow=async(type,id)=>{if(!confirm('حذف السجل؟'))return;await api(`/api/${type}/${id}`,{method:'DELETE'});showView(type);loadPublic()};
api('/api/me').then(x=>{if(x.authenticated)openAdmin()}).catch(()=>{});if('serviceWorker'in navigator)navigator.serviceWorker.register('/static/sw.js');
