(()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const origins=window.BUNYAN_API_ORIGINS||[window.BUNYAN_API_ORIGIN||'https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
  const token=()=>sessionStorage.getItem('bunyan_token')||'';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmtDate=v=>v?new Date(v).toLocaleString('ar-SD',{dateStyle:'medium',timeStyle:'short'}):'—';
  const money=(v,c)=>`${Number(v||0).toLocaleString('en-GB')} ${esc(c||'')}`;
  async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';if(typeof options.body==='object')options.body=JSON.stringify(options.body)}let last;for(const base of origins){try{const r=await fetch(base+path,{...options,headers,cache:'no-store'});const t=await r.text();let d={};try{d=t?JSON.parse(t):{}}catch{d={message:t}}if(!r.ok)throw new Error(d.error||d.message||`فشل الطلب (${r.status})`);return d}catch(e){last=e}}throw last||new Error('تعذر الاتصال بالخادم')}
  const statusText={pending:'قيد المراجعة',verified:'موثقة',rejected:'مرفوضة'};
  async function setStatus(id,status){await api(`/api/donations/${id}/status`,{method:'PATCH',body:{status}});await renderFinance()}
  function receiptNumber(d){return `BN-${new Date(d.created_at||Date.now()).getFullYear()}-${String(d.id||'').replace(/-/g,'').slice(0,10).toUpperCase()}`}
  function printReceipt(d){const no=receiptNumber(d),w=window.open('','_blank','width=850,height=1100');if(!w)return alert('اسمح بفتح النوافذ لطباعة السند.');w.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><title>${no}</title><style>body{font-family:Tahoma,Arial;margin:0;background:#eee;color:#10231f}.sheet{width:190mm;min-height:260mm;margin:12mm auto;background:white;padding:18mm;box-sizing:border-box}.head{display:flex;justify-content:space-between;align-items:start;border-bottom:3px solid #d7aa4b;padding-bottom:18px}.brand h1{margin:0;color:#0d3028}.brand p{margin:5px 0;color:#687571}.no{font-weight:bold}.badge{display:inline-block;padding:7px 12px;border-radius:999px;background:#e5f8ed;color:#116b3b}.grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:28px 0}.item{border:1px solid #dfe5e1;padding:14px;border-radius:10px}.item small{display:block;color:#687571;margin-bottom:8px}.amount{font-size:30px;color:#987125}.foot{margin-top:60px;border-top:1px solid #ddd;padding-top:18px;color:#687571}.actions{margin:20px;text-align:center}@media print{body{background:#fff}.sheet{margin:0;width:auto;min-height:auto}.actions{display:none}}</style></head><body><div class="actions"><button onclick="print()">طباعة / حفظ PDF</button></div><main class="sheet"><div class="head"><div class="brand"><h1>بُنْيَان</h1><p>مؤسسة شمس الأنبياء للتنمية</p></div><div><div class="no">سند قبض رقم: ${no}</div><p>${fmtDate(d.created_at)}</p><span class="badge">${statusText[d.status]||d.status}</span></div></div><h2>سند استلام مساهمة</h2><div class="grid"><div class="item"><small>اسم المساهم</small><strong>${esc(d.donor||'—')}</strong></div><div class="item"><small>رقم الهاتف</small><strong>${esc(d.phone||'—')}</strong></div><div class="item"><small>المشروع</small><strong>${esc(d.project_name||'دعم عام')}</strong></div><div class="item"><small>طريقة الدفع</small><strong>${esc(d.method||'—')}</strong></div><div class="item"><small>رقم المرجع</small><strong>${esc(d.reference||'—')}</strong></div><div class="item"><small>المبلغ المستلم</small><strong class="amount">${money(d.amount,d.currency)}</strong></div></div><p>نشهد باستلام المساهمة الموضحة أعلاه، ويصدر هذا السند إلكترونيًا من منصة بُنْيَان.</p><div class="foot">رمز التحقق: ${esc(d.id)}<br>هذا المستند لا يُعد توثيقًا نهائيًا إلا عندما تكون حالة العملية «موثقة».</div></main></body></html>`);w.document.close()}
  function donationCard(d){return `<article class="fin-card"><div class="fin-top"><div><small>${receiptNumber(d)}</small><h3>${esc(d.donor||'مساهم')}</h3></div><span class="fin-status s-${esc(d.status)}">${statusText[d.status]||esc(d.status)}</span></div><div class="fin-amount">${money(d.amount,d.currency)}</div><p>${esc(d.project_name||'دعم عام')} · ${fmtDate(d.created_at)}</p><div class="fin-actions"><button class="primary" data-receipt="${d.id}">سند قبض PDF</button><select data-status="${d.id}"><option value="pending" ${d.status==='pending'?'selected':''}>قيد المراجعة</option><option value="verified" ${d.status==='verified'?'selected':''}>موثقة</option><option value="rejected" ${d.status==='rejected'?'selected':''}>مرفوضة</option></select></div></article>`}
  async function renderFinance(){const c=$('#dashContent'),t=$('#dashTitle');if(!c)return;t.textContent='المركز المالي والشفافية';c.innerHTML='<p>جاري تحميل البيانات المالية...</p>';try{const rows=await api('/api/donations');const totals={};rows.filter(x=>x.status==='verified').forEach(x=>totals[x.currency]=(totals[x.currency]||0)+Number(x.amount||0));c.innerHTML=`<section class="fin-hero"><div><span>BUNYAN FINANCE OS</span><h3>المركز المالي والشفافية</h3><p>توثيق المساهمات، إصدار سندات القبض، ومراجعة الأداء المالي.</p></div><button class="primary" id="finExport">تصدير CSV</button></section><div class="fin-kpis"><article><small>إجمالي العمليات</small><b>${rows.length}</b></article><article><small>قيد المراجعة</small><b>${rows.filter(x=>x.status==='pending').length}</b></article><article><small>الموثقة</small><b>${rows.filter(x=>x.status==='verified').length}</b></article></div><section class="fin-totals"><h3>المبالغ الموثقة حسب العملة</h3>${Object.entries(totals).length?Object.entries(totals).map(([k,v])=>`<div><span>${k}</span><strong>${Number(v).toLocaleString('en-GB')}</strong></div>`).join(''):'<p>لا توجد مبالغ موثقة بعد.</p>'}</section><div class="fin-grid">${rows.length?rows.map(donationCard).join(''):'<p>لا توجد مساهمات.</p>'}</div>`;$$('[data-status]').forEach(s=>s.onchange=()=>setStatus(s.dataset.status,s.value));$$('[data-receipt]').forEach(b=>b.onclick=()=>printReceipt(rows.find(x=>x.id===b.dataset.receipt)));$('#finExport').onclick=()=>{const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['receipt,donor,phone,amount,currency,project,status,date',...rows.map(d=>[receiptNumber(d),d.donor,d.phone,d.amount,d.currency,d.project_name,statusText[d.status]||d.status,d.created_at].map(q).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}));a.download=`bunyan-finance-${new Date().toISOString().slice(0,10)}.csv`;a.click()}}catch(e){c.innerHTML=`<div class="error-msg">${esc(e.message)}</div>`}}
  function install(){const aside=$('#dash aside');if(!aside||$('#financeCenterBtn'))return;const before=$('#backup')||$('#logout');const b=document.createElement('button');b.id='financeCenterBtn';b.textContent='المركز المالي';aside.insertBefore(b,before);b.onclick=renderFinance}
  const timer=setInterval(()=>{if($('#dash aside')){install();clearInterval(timer)}},300);window.renderFinanceCenter=renderFinance;
})();