(function(){
  const roleName={admin:'مدير كامل',manager:'مدير عمليات',staff:'موظف',viewer:'مشاهدة فقط'};
  async function api(path,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(state.token)headers.Authorization=`Bearer ${state.token}`;const res=await fetch(`${API}${path}`,{...options,headers});const text=await res.text();let data=null;try{data=text?JSON.parse(text):null}catch{data={error:text}}if(!res.ok)throw new Error(data?.error||`فشل الاتصال (${res.status})`);return data}
  function installMenu(){const aside=$('#dash aside');if(!aside||$('#globalSystemBtn'))return;const logout=$('#logout');[['globalSystemBtn','مركز النظام'],['globalUsersBtn','المستخدمون والصلاحيات'],['globalAuditBtn','سجل النشاط']].forEach(([id,label])=>{const b=document.createElement('button');b.id=id;b.textContent=label;aside.insertBefore(b,logout)});$('#globalSystemBtn').onclick=systemView;$('#globalUsersBtn').onclick=usersView;$('#globalAuditBtn').onclick=auditView}
  async function systemView(){dashTitle.textContent='مركز النظام العالمي';loading(dashContent);try{const x=await api('/api/admin/system');dashContent.innerHTML=`<div class="global-hero"><div><span>بُنْيَان GLOBAL OS</span><h3>منصة حوكمة جاهزة للنمو</h3><p>تشغيل، صلاحيات، تدقيق، وقياس صحة النظام من مركز واحد.</p></div><strong>${x.database_ms} ms</strong></div><div class="global-kpis"><article><small>المستخدمون</small><b>${x.active_users}/${x.users}</b></article><article><small>المشروعات</small><b>${x.projects}</b></article><article><small>الطلبات</small><b>${x.requests}</b></article><article><small>المساهمات</small><b>${x.donations}</b></article><article><small>إشعارات التحويل</small><b>${x.donation_receipts}</b></article><article><small>نشاط 24 ساعة</small><b>${x.actions_24h}</b></article></div><div class="global-status"><h3>حالة البنية</h3><p><span class="health-dot"></span> قاعدة البيانات متصلة</p><p>إصدار API: ${esc(x.api_version)}</p><p>حجم قاعدة البيانات: ${Math.max(1,Math.round(Number(x.database_bytes)/1024/1024))} MB</p><p>آخر فحص: ${date(x.time)}</p></div>`}catch(err){showError(dashContent,err)}}
  async function usersView(){dashTitle.textContent='المستخدمون والصلاحيات';loading(dashContent);try{const rows=await api('/api/admin/users');dashContent.innerHTML=`<div class="dash-actions"><button class="primary" id="newUserBtn">إضافة مستخدم</button><span class="count-badge">${rows.length} مستخدم</span></div><div class="user-grid">${rows.map(u=>`<article><div><span class="status-pill ${u.is_active?'s-accepted':'s-rejected'}">${u.is_active?'نشط':'معطل'}</span><h3>${esc(u.name)}</h3><p>${esc(u.email)}</p><small>${esc(roleName[u.role]||u.role)}</small></div><div class="user-actions"><select data-role="${u.id}">${Object.entries(roleName).map(([v,l])=>`<option value="${v}" ${u.role===v?'selected':''}>${l}</option>`).join('')}</select><button class="mini details" data-pass="${u.id}">تعيين كلمة سر</button><button class="mini ${u.is_active?'danger':'primary'}" data-toggle="${u.id}" data-active="${u.is_active}">${u.is_active?'تعطيل':'تفعيل'}</button></div></article>`).join('')}</div>`;$('#newUserBtn').onclick=createUser;$$('[data-role]').forEach(s=>s.onchange=()=>updateUser(s.dataset.role,{role:s.value}));$$('[data-pass]').forEach(b=>b.onclick=()=>resetPassword(b.dataset.pass));$$('[data-toggle]').forEach(b=>b.onclick=()=>updateUser(b.dataset.toggle,{isActive:b.dataset.active!=='true'}))}catch(err){showError(dashContent,err)}}
  async function createUser(){const name=prompt('اسم المستخدم');if(!name)return;const email=prompt('البريد الإلكتروني');if(!email)return;const role=prompt('الصلاحية: admin أو manager أو staff أو viewer','staff');if(!role)return;const password=prompt('كلمة سر مؤقتة لا تقل عن 10 أحرف');if(!password)return;try{await api('/api/admin/users',{method:'POST',body:JSON.stringify({name,email,role,password})});await usersView()}catch(err){alert(err.message)}}
  async function updateUser(id,body){try{await api(`/api/admin/users/${id}`,{method:'PATCH',body:JSON.stringify(body)});await usersView()}catch(err){alert(err.message)}}
  async function resetPassword(id){const password=prompt('كلمة السر الجديدة لا تقل عن 10 أحرف');if(!password)return;try{await api(`/api/admin/users/${id}/reset-password`,{method:'POST',body:JSON.stringify({password})});alert('تم تعيين كلمة السر الجديدة')}catch(err){alert(err.message)}}
  async function auditView(){dashTitle.textContent='سجل النشاط والتدقيق';loading(dashContent);try{const rows=await api('/api/admin/audit?limit=150');dashContent.innerHTML=`<div class="dash-actions"><span class="count-badge">آخر ${rows.length} عملية</span><button class="primary" id="auditExport">تصدير CSV</button></div><div class="table"><table><tr><th>الوقت</th><th>المستخدم</th><th>العملية</th><th>القسم</th><th>العنوان</th></tr>${rows.map(r=>`<tr><td>${date(r.created_at)}</td><td>${esc(r.user_name||'النظام')}</td><td>${esc(r.action)}</td><td>${esc(r.entity_type)}</td><td>${esc(r.ip_address||'—')}</td></tr>`).join('')}</table></div>`;$('#auditExport').onclick=()=>exportAudit(rows)}catch(err){showError(dashContent,err)}}
  function exportAudit(rows){const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['time,user,email,action,section,entity,ip',...rows.map(r=>[r.created_at,r.user_name,r.user_email,r.action,r.entity_type,r.entity_id,r.ip_address].map(q).join(','))].join('\n');const blob=new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bunyan-audit-${Date.now()}.csv`;a.click();URL.revokeObjectURL(a.href)}
  const timer=setInterval(()=>{if($('#dash aside')){installMenu();clearInterval(timer)}},300);
})();
