(()=>{
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const origins=window.BUNYAN_API_ORIGINS||[window.BUNYAN_API_ORIGIN||'https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
  let activeOrigin=sessionStorage.getItem('bunyan_api_origin')||origins[0];
  const token=()=>sessionStorage.getItem('bunyan_token')||'';
  const arDate=v=>v?new Date(v).toLocaleString('ar-SD',{dateStyle:'medium',timeStyle:'short'}):'—';
  const resources={
    beneficiaries:{title:'إدارة المستفيدين',singular:'مستفيد',fields:[['name','الاسم','text',true],['phone','الهاتف','text',false],['service','الخدمة','text',true],['status','الحالة','select',true,['new','review','accepted','completed','rejected']],['notes','ملاحظات','textarea',false]]},
    volunteers:{title:'إدارة المتطوعين',singular:'متطوع',fields:[['name','الاسم','text',true],['phone','الهاتف','text',false],['email','البريد','email',false],['skill','المهارة','text',true],['hours','الساعات','number',false],['status','الحالة','select',true,['new','active','inactive','completed']]]},
    requests:{title:'طلبات المشاركة والشراكات',singular:'طلب',fields:[['name','الاسم','text',true],['phone','الهاتف','text',true],['role','نوع المشاركة','text',true],['message','الرسالة','textarea',false],['status','الحالة','select',true,['new','review','accepted','rejected']]]}
  };
  const statusText={new:'جديد',review:'قيد المراجعة',accepted:'مقبول',rejected:'مرفوض',completed:'مكتمل',active:'نشط',inactive:'غير نشط'};
  async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';if(typeof options.body==='object')options.body=JSON.stringify(options.body)}let last;for(const base of [activeOrigin,...origins.filter(x=>x!==activeOrigin)]){try{const res=await fetch(base+path,{...options,headers,cache:'no-store'});const text=await res.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!res.ok){const e=new Error(data.error||data.message||`فشل الطلب (${res.status})`);e.status=res.status;throw e}activeOrigin=base;sessionStorage.setItem('bunyan_api_origin',base);return data}catch(e){last=e;if(e.status>=400&&e.status<500&&e.status!==401&&e.status!==403)throw e}}throw last||new Error('تعذر الاتصال بالخادم')}
  function fieldInput(field,item={}){const [name,label,type,required,options]=field;const value=item[name]??'';if(type==='textarea')return `<label>${label}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea></label>`;if(type==='select')return `<label>${label}<select name="${name}" ${required?'required':''}>${options.map(v=>`<option value="${v}" ${value===v?'selected':''}>${statusText[v]||v}</option>`).join('')}</select></label>`;return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`}
  function openEditor(type,item={}){const def=resources[type];document.querySelector('.suite-modal')?.remove();const modal=document.createElement('div');modal.className='suite-modal';modal.innerHTML=`<form><button type="button" class="suite-close">×</button><h2>${item.id?'تعديل':'إضافة'} ${def.singular}</h2>${def.fields.map(f=>fieldInput(f,item)).join('')}<button class="primary">حفظ</button><small class="suite-msg"></small></form>`;document.body.appendChild(modal);modal.querySelector('.suite-close').onclick=()=>modal.remove();modal.onclick=e=>{if(e.target===modal)modal.remove()};modal.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,msg=f.querySelector('.suite-msg'),btn=f.querySelector('.primary'),body=Object.fromEntries(new FormData(f).entries());if('hours'in body)body.hours=Number(body.hours||0);try{btn.disabled=true;msg.textContent='جاري الحفظ...';await api(item.id?`/api/${type}/${item.id}`:`/api/${type}`,{method:item.id?'PATCH':'POST',body});modal.remove();renderResource(type)}catch(err){msg.textContent=err.message}finally{btn.disabled=false}}}
  async function removeItem(type,id){if(!confirm('هل تريد حذف هذا السجل نهائيًا؟'))return;try{await api(`/api/${type}/${id}`,{method:'DELETE'});renderResource(type)}catch(e){alert(e.message)}}
  async function renderResource(type){const def=resources[type],content=$('#dashContent'),title=$('#dashTitle');if(!content)return;title.textContent=def.title;content.innerHTML='<div class="loading">جاري التحميل...</div>';try{const rows=await api(`/api/${type}`);const cards=rows.map(r=>`<article class="suite-card"><span class="status-pill s-${esc(r.status||'new')}">${esc(statusText[r.status]||r.status||'جديد')}</span><h3>${esc(r.name||'بدون اسم')}</h3><p>${esc(r.service||r.skill||r.role||r.message||'')}</p><div class="suite-meta"><div><span>الهاتف</span><strong>${esc(r.phone||'—')}</strong></div><div><span>التاريخ</span><strong>${esc(arDate(r.created_at))}</strong></div></div><div class="suite-row-actions"><button class="mini primary" data-edit="${r.id}">تعديل</button><button class="mini danger" data-delete="${r.id}">حذف</button></div></article>`).join('');content.innerHTML=`<section class="suite-head"><div><span>BUNYAN GLOBAL OS</span><h3>${def.title}</h3><p>إدارة مؤسسية كاملة من الهاتف والكمبيوتر.</p></div><div class="suite-actions"><button class="primary" id="suiteAdd">+ إضافة ${def.singular}</button><button class="outline" id="suiteExport">تصدير CSV</button></div></section><div class="suite-kpis"><article><small>الإجمالي</small><strong>${rows.length}</strong></article><article><small>نشط/مقبول</small><strong>${rows.filter(x=>['active','accepted','completed'].includes(x.status)).length}</strong></article><article><small>قيد المراجعة</small><strong>${rows.filter(x=>['new','review'].includes(x.status)).length}</strong></article><article><small>مرفوض/معطل</small><strong>${rows.filter(x=>['rejected','inactive'].includes(x.status)).length}</strong></article></div><div class="suite-grid">${cards||'<div class="suite-empty">لا توجد بيانات حتى الآن.</div>'}</div>`;$('#suiteAdd').onclick=()=>openEditor(type);$('#suiteExport').onclick=()=>exportCsv(type,rows);$$('[data-edit]').forEach(b=>b.onclick=()=>openEditor(type,rows.find(x=>x.id===b.dataset.edit)));$$('[data-delete]').forEach(b=>b.onclick=()=>removeItem(type,b.dataset.delete));window.BunyanI18n?.refresh?.()}catch(e){content.innerHTML=`<div class="suite-error">${esc(e.message)}</div>`}}
  function exportCsv(type,rows){const def=resources[type],cols=def.fields.map(f=>f[0]);const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csv='\ufeff'+[cols.map(q).join(','),...rows.map(r=>cols.map(c=>q(r[c])).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`bunyan-${type}-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
  async function transparencyView(){const content=$('#dashContent'),title=$('#dashTitle');title.textContent='الشفافية والتقارير';content.innerHTML='<div class="loading">جاري التحميل...</div>';try{const [projects,donations]=await Promise.all([api('/api/projects'),api('/api/donations')]);const verified=donations.filter(d=>d.status==='verified');const totals={};verified.forEach(d=>{const key=d.currency||'SDG';totals[key]=(totals[key]||0)+Number(d.amount||0)});content.innerHTML=`<section class="suite-head"><div><span>PUBLIC ACCOUNTABILITY</span><h3>مركز الشفافية والتقارير</h3><p>ملخص المشاريع والمساهمات الموثقة دون خلط العملات.</p></div><div class="suite-actions"><button class="primary" id="printTransparency">طباعة التقرير</button></div></section><div class="suite-kpis"><article><small>المشروعات</small><strong>${projects.length}</strong></article><article><small>المساهمات</small><strong>${donations.length}</strong></article><article><small>الموثقة</small><strong>${verified.length}</strong></article><article><small>قيد المراجعة</small><strong>${donations.filter(d=>d.status==='pending').length}</strong></article></div><div class="suite-grid">${Object.entries(totals).map(([c,v])=>`<article class="suite-card"><small>إجمالي موثق</small><h3>${Number(v).toLocaleString('en-GB')} ${esc(c)}</h3></article>`).join('')||'<div class="suite-empty">لا توجد مساهمات موثقة بعد.</div>'}</div>`;$('#printTransparency').onclick=()=>window.print();window.BunyanI18n?.refresh?.()}catch(e){content.innerHTML=`<div class="suite-error">${esc(e.message)}</div>`}}
  function settingsView(){const content=$('#dashContent'),title=$('#dashTitle');title.textContent='الإعدادات';const dark=localStorage.getItem('bunyan_dark')==='1';const current=window.BunyanI18n?.getLanguage?.()||localStorage.getItem('bunyan_language')||'ar';content.innerHTML=`<section class="suite-head"><div><span>PLATFORM SETTINGS</span><h3>إعدادات بُنْيَان</h3><p>المظهر واللغة وإعدادات الجهاز.</p></div></section><div class="suite-grid"><article class="suite-card"><h3>الوضع الليلي</h3><p>تحسين القراءة في الإضاءة المنخفضة.</p><button class="primary" id="toggleDark">${dark?'إيقاف':'تشغيل'} الوضع الليلي</button></article><article class="suite-card"><h3>اللغة</h3><p>اختر لغة الواجهة، وسيتم تطبيقها على الموقع ولوحة الإدارة بالكامل.</p><button class="primary" id="toggleLang" data-language-toggle="true">${current==='ar'?'English':'العربية'}</button></article><article class="suite-card"><h3>تحديث التطبيق</h3><p>حذف الكاش المحلي وإعادة تحميل أحدث إصدار.</p><button class="primary" id="hardRefresh">تحديث كامل</button></article></div>`;$('#toggleDark').onclick=toggleDark;$('#hardRefresh').onclick=()=>{localStorage.removeItem('bunyan_cache_version');location.reload()};window.BunyanI18n?.refresh?.()}
  function toggleDark(){const on=!document.body.classList.contains('suite-dark');document.body.classList.toggle('suite-dark',on);localStorage.setItem('bunyan_dark',on?'1':'0');settingsView()}
  function install(){const aside=$('#dash aside');if(!aside||$('#suiteTransparencyBtn'))return;const anchor=$('#backup')||$('#logout');[['suiteTransparencyBtn','الشفافية والتقارير',transparencyView],['suiteSettingsBtn','الإعدادات',settingsView]].forEach(([id,label,fn])=>{const b=document.createElement('button');b.id=id;b.textContent=label;b.onclick=fn;aside.insertBefore(b,anchor)});const map={beneficiaries:'beneficiaries',volunteers:'volunteers',requests:'requests'};Object.entries(map).forEach(([view,type])=>{const b=$(`[data-view="${view}"]`);if(b)b.onclick=()=>renderResource(type)});if(localStorage.getItem('bunyan_dark')==='1')document.body.classList.add('suite-dark')}
  const timer=setInterval(()=>{if($('#dash aside')){install();clearInterval(timer)}},250);
})();