(function(){
  'use strict';
  var KEY='bunyan_language';
  var lang=localStorage.getItem(KEY)==='en'?'en':'ar';
  var pairs=[
    ['BUNYAN','بُنْيَان'],['Shams Al-Anbiya Foundation for Development','مؤسسة شمس الأنبياء للتنمية'],['People First','الإنسان أولاً'],['Building people here','هنا يُبنى الإنسان'],
    ['Overview','نظرة عامة'],['Projects','المشروعات'],['Beneficiaries','المستفيدون'],['Volunteers','المتطوعون'],['Settings','الإعدادات'],['View Website','عرض الموقع'],['Finance Centre','المركز المالي'],['Transparency & Reports','الشفافية والتقارير'],['Project Transparency','شفافية المشروعات'],['Project Management','إدارة المشروعات'],['New Project','مشروع جديد'],['Create New Project +','إنشاء مشروع جديد +'],['Create New Project','إنشاء مشروع جديد'],['Add Project','إضافة مشروع'],['Dashboard','لوحة التحكم'],['Reports','التقارير'],['Donations','التبرعات'],['Contributions','المساهمات'],['Expenses','المصروفات'],['Documents','المستندات'],['System Status','حالة النظام'],['Backup & Audit','النسخ الاحتياطي والتدقيق'],['Download Backup','تنزيل نسخة احتياطية'],['Logout','تسجيل الخروج'],['Cloud Administration','الإدارة السحابية'],
    ['Platform Settings','إعدادات بُنْيَان'],['Appearance, language and device settings.','المظهر واللغة وإعدادات الجهاز.'],['Dark Mode','الوضع الليلي'],['Improve readability in low light.','تحسين القراءة في الإضاءة المنخفضة.'],['Enable Dark Mode','تشغيل الوضع الليلي'],['Disable Dark Mode','إيقاف الوضع الليلي'],['Language','اللغة'],['Arabic is the primary interface, with instant translation for main headings.','الواجهة العربية هي الأساسية، مع طبقة ترجمة فورية للعناوين الرئيسية.'],['Arabic is the primary interface, with instant translation across the system.','الواجهة العربية هي الأساسية، مع ترجمة فورية لجميع عناصر النظام.'],['App Update','تحديث التطبيق'],['Clear local cache and reload the latest version.','حذف الكاش المحلي وإعادة تحميل أحدث إصدار.'],['Full Update','تحديث كامل'],['Check for Update','التحقق من التحديث'],
    ['About Us','من نحن'],['Programs','البرامج'],['News','الأخبار'],['Join Us','شارك معنا'],['Contact Us','اتصل بنا'],['Admin Dashboard','لوحة الإدارة'],['Impact','الأثر'],['Transparency','الشفافية'],['From local community to sustainable impact','من المجتمع المحلي إلى أثر مستدام'],['We build people','نبني الإنسان'],['to build the future','ليَبني المستقبل'],['View Our Projects','شاهد مشروعاتنا'],['Join BUNYAN','انضم إلى البُنْيَان'],['A Sudanese development ecosystem combining governance, transparency, knowledge and field work to create real, measurable and sustainable impact.','بُنْيَان منظومة سودانية للتنمية تجمع الحوكمة والشفافية والمعرفة والعمل الميداني لصناعة أثر حقيقي قابل للقياس والاستمرار.'],
    ['Development Fields','مجالات تنموية'],['Target Initiatives','مبادرة مستهدفة'],['Target Volunteers','متطوعاً مستهدفاً'],['Target Beneficiaries','مستفيد مستهدف'],['A foundation managed by systems and driven by community values','مؤسسة تُدار بالنظام وتتحرك بقيم المجتمع'],['We build a development model that begins with people’s real needs, documents resources, decisions and results, and gives every contributor, volunteer and partner a clear view of impact.','نؤسس نموذجاً تنموياً يبدأ من احتياجات الناس الحقيقية، ويوثق الموارد والقرارات والنتائج، ويمنح كل مساهم ومتطوع وشريك صورة واضحة عن الأثر.'],['People First','الإنسان أولاً'],['Transparency','الشفافية'],['Justice','العدالة'],['Sustainability','الاستدامة'],
    ['BUNYAN Programs','برامج بُنْيَان'],['Four pathways to build a stronger community','أربعة مسارات لبناء مجتمع أقوى'],['Education and Knowledge','التعليم والمعرفة'],['Supporting schools, training and digital libraries.','دعم المدارس، التدريب، والمكتبات الرقمية.'],['Health and Community','الصحة والمجتمع'],['Preventive care and maternal and child health.','الرعاية الوقائية وصحة الأم والطفل.'],['Economic Empowerment','التمكين الاقتصادي'],['Skills and small enterprises.','المهارات والمشروعات الصغيرة.'],['Digital Transformation','التحول الرقمي'],['Platforms and data serving development.','منصات وبيانات لخدمة التنمية.'],
    ['From idea to visible impact','من الفكرة إلى أثر يُرى'],['Equipping School Digital Libraries','تجهيز المكتبات الرقمية المدرسية'],['Providing schools with computing equipment and cloud connectivity to ensure continuous digital education for students.','تزويد المدارس بمستلزمات الحوسبة والربط السحابي لضمان استمرار التعليم الرقمي للطلاب.'],['Preventive Clinics and Primary Care','العيادات الوقائية والرعاية الأولية'],['Providing preventive care and maternal and child health services through field doctors and volunteers in developing areas.','تقديم الرعاية الوقائية وصحة الأم والطفل عبر أطباء ومتطوعين ميدانيين في المناطق النامية.'],['Supporting Small Productive Projects','دعم المشاريع الإنتاجية الصغيرة'],['Financing and training productive families in local production and marketing skills to ensure sustainability.','تمويل وتدريب الأسر المنتجة على مهارات الإنتاج المحلي والتسويق لضمان الاستدامة.'],['Contribute to the Project','ساهم في المشروع'],['View Project Details','عرض تفاصيل المشروع'],['Budget','الميزانية'],['Implementation Status','حالة التنفيذ'],['Pending Publication','قيد النشر'],['Preparation Stage','في مرحلة الإعداد'],['Verified','موثق'],['Last Update: Not Published','آخر تحديث: لم يُنشر'],
    ['Impact in Numbers','الأثر بالأرقام'],['We separate ambition from results','نفصل بين الطموح والنتيجة'],['Published targets represent our plan, while achieved results appear only after documentation and review.','الأهداف المعلنة تعبّر عن خطتنا، أما النتائج المتحققة فلا تُعرض إلا بعد التوثيق والمراجعة.'],['Target Goals','الأهداف المستهدفة'],['Verified Results','النتائج الموثقة'],['Development Fields','المجالات التنموية'],['Education, health, economic empowerment and digital transformation','تعليم، صحة، تمكين اقتصادي، تحول رقمي'],['Target Initiatives','المبادرات المستهدفة'],['Within the phased expansion plan','ضمن خطة التوسع المرحلية'],['Target Volunteers','المتطوعون المستهدفون'],['Community volunteer network','شبكة تطوع مجتمعية'],['Target Beneficiaries','المستفيدون المستهدفون'],['Initial plan estimate','تقدير أولي للخطة'],['Completed Projects','المشروعات المكتملة'],['Pending Documentation','قيد التوثيق'],['No figure will be published before approval','لن يُنشر رقم قبل اعتماده'],['Verified Beneficiaries','المستفيدون الموثقون'],['According to project records','بحسب سجلات المشروعات'],['Verified Contributions','المساهمات المؤكدة'],['After matching payment notifications','بعد مطابقة إشعارات الدفع'],['Volunteer Hours','ساعات التطوع'],['After approving team reports','بعد اعتماد تقارير الفرق'],
    ['Public Transparency','الشفافية العامة'],['Where does the support go?','أين يذهب الدعم؟'],['This dashboard publishes verified contributions, documented expenses and project progress. No financial value is displayed before reconciliation and approval.','هذه اللوحة مخصصة لنشر المساهمات المؤكدة والمصروفات الموثقة وتقدم المشروعات. لا تُعرض أي قيمة مالية قبل مطابقتها واعتمادها.'],['Verified Contribution Total','إجمالي المساهمات المؤكدة'],['Loading verified data…','جاري تحميل البيانات الموثقة…'],['Verified contribution records only','المساهمات المعتمدة في النظام فقط'],['Documented Expense Total','إجمالي المصروفات الموثقة'],['Not Enabled Yet','غير مفعّل بعد'],['Expense approval cycle is under development','دورة اعتماد المصروفات قيد التطوير'],['Available Project Balance','الرصيد المتاح للمشروعات'],['Cannot be calculated before expense documentation','لا يُحسب قبل توثيق المصروفات'],['Latest Financial Update','آخر تحديث مالي'],['Loading…','جاري التحميل…'],['Based on the latest verified contribution','بحسب آخر مساهمة موثقة'],['BUNYAN Rule:','قاعدة بُنْيَان:'],['A target is not an achievement, a pledge is not a verified contribution, and an expense is not approved without documentation.','الهدف ليس رقمًا محققًا، والتعهد ليس مساهمة مؤكدة، والمصروف لا يُعتمد بلا مستند.'],['Verified Contributions by Currency','المساهمات الموثقة حسب العملة'],['No verified contribution has been published yet.','لم تُنشر مساهمة موثقة بعد.'],['Verified Transactions','عمليات موثقة'],['No personal contributor data is displayed.','لا تُعرض أي بيانات شخصية للمساهمين.'],['Could not load verified data','تعذر تحميل البيانات الموثقة'],['The figures were hidden to prevent displaying inaccurate information.','تم إخفاء الأرقام منعًا لعرض معلومات غير دقيقة.'],
    ['Location','الموقع'],['To Be Determined','قيد التحديد'],['Number of Beneficiaries','عدد المستفيدين'],['Pending Verification','قيد التوثيق'],['Pending Approval','قيد الاعتماد'],['The scope of work, implementation stages, field photos, documents, expenses and latest approved update will be added here.','سيُضاف هنا نطاق العمل، مراحل التنفيذ، الصور الميدانية، المستندات، المصروفات وآخر تحديث معتمد.'],['Close','إغلاق'],
    ['Latest News','آخر الأخبار'],['BUNYAN Pulse','نبض بُنْيَان'],['Launch of BUNYAN Digital Development Platform','إطلاق منصة بُنْيَان الرقمية للتنمية'],['Launching the cloud governance and transparency system to directly connect contributors and volunteers with field projects.','تدشين النظام السحابي للحوكمة والشفافية لربط المساهمين والمتطوعين بالمشاريع الميدانية مباشرة.'],['July 2026','يوليو 2026'],['Assessment of Schools Targeted for Digital Development Begins','بدء حصر المدارس المستهدفة للتطوير الرقمي'],['Field teams begin assessing technical needs and providing educational computing equipment.','انطلاق الفرق الميدانية لتقييم الاحتياجات التقنية وتوفير أجهزة الحوسبة التعليمية.'],
    ['Support Creates Impact','الدعم يصنع أثراً'],['Contribute to a Verified Project','ساهم في مشروع موثّق'],['Register your contribution now; it will appear in the dashboard with the project, currency and payment method.','سجّل مساهمتك الآن، وستظهر في لوحة الإدارة مع المشروع والعملة وطريقة الدفع.'],['Register Contribution','تسجيل مساهمة'],['Participation Makes a Difference','المشاركة تصنع الفرق'],['You have a place in this BUNYAN','لك مكان في هذا البُنْيَان'],['As a volunteer, expert, supporter or partner.','متطوعاً أو خبيراً أو داعماً أو شريكاً.'],['Full Name','الاسم الكامل'],['Phone Number','رقم الهاتف'],['I want to volunteer','أرغب في التطوع'],['I want to partner','أرغب في الشراكة'],['I want to support a project','أرغب في دعم مشروع'],['Send Request','إرسال الطلب'],['Direct Contact','تواصل مباشر'],['Your message reaches the BUNYAN team immediately','رسالتك تصل فورًا إلى فريق بُنْيَان'],['For partnerships, enquiries, suggestions and reports. The message is saved in the system and an immediate alert is sent by email and Telegram.','للشراكات، الاستفسارات، المقترحات والبلاغات. تُحفظ الرسالة في النظام ويصل تنبيه فوري إلى البريد وتيليجرام.'],['Leave this field empty','اترك هذا الحقل فارغًا'],['Email Address (optional)','البريد الإلكتروني (اختياري)'],['Phone or WhatsApp (optional)','رقم الهاتف أو واتساب (اختياري)'],['Message Subject','موضوع الرسالة'],['Write your message clearly','اكتب رسالتك بوضوح'],['Send Message','إرسال الرسالة'],
    ['Admin Login','دخول لوحة الإدارة'],['Administrator name (first setup only)','اسم المدير (مطلوب لأول إعداد فقط)'],['Email Address','البريد الإلكتروني'],['Password','كلمة المرور'],['Login','دخول'],['Create First Administrator Account','إنشاء أول حساب مدير'],['Use the create administrator button only once during initial setup.','استخدم زر إنشاء المدير مرة واحدة فقط عند الإعداد الأول.'],['Authorised administration access only','دخول الإدارة المصرح فقط'],
    ['Contributor Name','اسم المساهم'],['Phone Number (optional)','رقم الهاتف (اختياري)'],['Amount','المبلغ'],['Project Name','اسم المشروع'],['Payment Method','طريقة الدفع'],['Reference Number (optional)','رقم المرجع (اختياري)'],['Attach Transfer Receipt','إرفاق إشعار التحويل'],['Image or PDF — maximum 3 MB','صورة أو PDF — الحد الأقصى 3 ميغابايت'],['Save Contribution','حفظ المساهمة'],
    ['Search','بحث'],['Save','حفظ'],['Cancel','إلغاء'],['Delete','حذف'],['Edit','تعديل'],['Preview','معاينة'],['Share Project','مشاركة المشروع'],['Copy Link','نسخ الرابط'],['Copied!','تم النسخ!'],['Loading...','جاري التحميل...'],['No data available','لا توجد بيانات'],['Create Project','إنشاء مشروع'],['Project Name','اسم المشروع'],['Executive Summary','الملخص التنفيذي'],['Status','الحالة'],['Progress','نسبة الإنجاز'],['Budget','الميزانية'],['Currency','العملة'],['Target Beneficiaries','عدد المستفيدين المستهدف'],['Publish project on public website','نشر المشروع في الموقع العام'],['Active','نشط'],['Completed','مكتمل'],['Paused','متوقف مؤقتًا'],['Planning','قيد التخطيط'],['Draft','مسودة'],['Public','منشور'],['Private','غير منشور'],
    ['Project expenses and documents','مصروفات المشروع ومستنداته'],['Add expense','إضافة مصروف'],['Upload document','رفع مستند'],['Amount','المبلغ'],['Date','التاريخ'],['Category','التصنيف'],['Notes','ملاحظات'],['File','الملف'],['Download','تنزيل'],['Receipt','فاتورة أو إيصال'],['Pending','قيد المراجعة'],['Verified','موثقة'],['Rejected','مرفوضة'],['Financial Centre and Transparency','المركز المالي والشفافية'],['Documenting contributions, issuing receipts and reviewing financial performance.','توثيق المساهمات، إصدار سندات القبض، ومراجعة الأداء المالي.'],['Export CSV','تصدير CSV'],['Total Transactions','إجمالي العمليات'],['Verified Amounts by Currency','المبالغ الموثقة حسب العملة'],['No verified amounts yet.','لا توجد مبالغ موثقة بعد.'],['No contributions.','لا توجد مساهمات.'],['Receipt PDF','سند قبض PDF'],['General Support','دعم عام'],['Contributor','مساهم'],['Loading financial data...','جاري تحميل البيانات المالية...'],['Could not connect to the server','تعذر الاتصال بالخادم'],['Request failed','فشل الطلب']
  ];
  var arToEn={},enToAr={},i;
  for(i=0;i<pairs.length;i++){enToAr[pairs[i][0]]=pairs[i][1];arToEn[pairs[i][1]]=pairs[i][0];}
  function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
  function convert(v){
    var c=clean(v),m=lang==='en'?arToEn:enToAr,n=m[c];
    if(!n)return v;
    var s=String(v),a=(s.match(/^\s*/)||[''])[0],b=(s.match(/\s*$/)||[''])[0];
    return a+n+b;
  }
  function closestNoI18n(el){while(el&&el.nodeType===1){if(el.getAttribute&&el.getAttribute('data-no-i18n')!==null)return true;el=el.parentNode;}return false;}
  function nodeTranslate(n){
    if(!n)return;
    if(n.nodeType===3){var p=n.parentNode;if(!p||/^(SCRIPT|STYLE|TEXTAREA)$/i.test(p.tagName)||closestNoI18n(p))return;var x=convert(n.nodeValue);if(x!==n.nodeValue)n.nodeValue=x;return;}
    if(n.nodeType!==1||closestNoI18n(n))return;
    var attrs=['placeholder','title','aria-label','value'];
    for(var j=0;j<attrs.length;j++){var a=attrs[j];if(n.hasAttribute&&n.hasAttribute(a)){if(a==='value'&&!/^(BUTTON|INPUT)$/i.test(n.tagName))continue;var old=n.getAttribute(a),next=convert(old);if(next!==old)n.setAttribute(a,next);}}
  }
  function walk(root){
    if(!root)return;nodeTranslate(root);
    var w=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT,null,false),n;
    while((n=w.nextNode()))nodeTranslate(n);
    updateToggle();removeDuplicateHeading();
  }
  function updateToggle(){
    var list=document.querySelectorAll('button,a');
    for(var i=0;i<list.length;i++){
      var el=list[i],t=clean(el.textContent);
      if(el.getAttribute('data-language-toggle')==='true'||/Switch to English|Switch to Arabic|التبديل إلى الإنجليزية|التبديل إلى العربية|English\s*\/|\/\s*English/i.test(t)){
        el.setAttribute('data-language-toggle','true');
        el.textContent=lang==='ar'?'English':'العربية';
        el.setAttribute('aria-label',lang==='ar'?'Switch to English':'التبديل إلى العربية');
      }
    }
  }
  function removeDuplicateHeading(){
    var cards=document.querySelectorAll('.settings-hero,.settings-banner,.platform-settings');
    for(var i=0;i<cards.length;i++){var hs=cards[i].querySelectorAll('h1,h2,h3');if(hs.length>1&&clean(hs[0].textContent).toLowerCase()===clean(hs[1].textContent).toLowerCase())hs[0].style.display='none';}
  }
  function applyDirection(){
    document.documentElement.lang=lang;
    document.documentElement.dir=lang==='ar'?'rtl':'ltr';
    if(document.body){document.body.dir=lang==='ar'?'rtl':'ltr';document.body.classList.remove('lang-ar','lang-en');document.body.classList.add(lang==='ar'?'lang-ar':'lang-en');}
    document.title=lang==='ar'?'بُنْيَان | مؤسسة شمس الأنبياء للتنمية':'BUNYAN | Shams Al-Anbiya Foundation for Development';
  }
  function setLanguage(next){
    lang=next==='en'?'en':'ar';localStorage.setItem(KEY,lang);applyDirection();
    if(document.body)walk(document.body);
    try{window.dispatchEvent(new CustomEvent('bunyan:languagechange',{detail:{lang:lang}}));}catch(e){}
    setTimeout(function(){if(document.body)walk(document.body);},80);
    setTimeout(function(){if(document.body)walk(document.body);},500);
  }
  document.addEventListener('click',function(e){var el=e.target;while(el&&el!==document&&!(el.getAttribute&&el.getAttribute('data-language-toggle')==='true'))el=el.parentNode;if(!el||el===document)return;e.preventDefault();e.stopPropagation();setLanguage(lang==='ar'?'en':'ar');},true);
  var timer=null;
  if(window.MutationObserver){new MutationObserver(function(records){clearTimeout(timer);timer=setTimeout(function(){for(var r=0;r<records.length;r++){var rec=records[r];if(rec.type==='characterData'){nodeTranslate(rec.target);continue;}for(var k=0;k<rec.addedNodes.length;k++){var n=rec.addedNodes[k];if(n.nodeType===1)walk(n);else if(n.nodeType===3)nodeTranslate(n);}}updateToggle();},40);}).observe(document.documentElement,{childList:true,subtree:true,characterData:true,attributes:true,attributeFilter:['placeholder','title','aria-label','value']);}
  function init(){applyDirection();setLanguage(lang);setTimeout(function(){walk(document.body);},200);setTimeout(function(){walk(document.body);},900);setTimeout(function(){walk(document.body);},2200);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.BunyanI18n={getLanguage:function(){return lang;},setLanguage:setLanguage,t:function(key){return (lang==='en'?arToEn:enToAr)[key]||key;},refresh:function(){walk(document.body);}};
})();