(()=>{
'use strict';
const KEY='bunyan_language';
let lang=localStorage.getItem(KEY)==='en'?'en':'ar';
let applying=false,scheduled=false;
const textState=new WeakMap(),attrState=new WeakMap();
const D={
'بُنْيَان':'BUNYAN','مؤسسة شمس الأنبياء للتنمية':'Shams Al-Anbiya Foundation for Development','هنا يُبنى الإنسان':'Building people here','الإنسان أولاً':'People First',
'من نحن':'About Us','البرامج':'Programs','المشروعات':'Projects','الأخبار':'News','شارك معنا':'Join Us','اتصل بنا':'Contact Us','لوحة الإدارة':'Admin Dashboard','الأثر':'Impact','الشفافية':'Transparency','خريطة الأثر':'Impact Map',
'من المجتمع المحلي إلى أثر مستدام':'From local community to sustainable impact','نبني الإنسان':'We build people','ليَبني المستقبل':'to build the future','شاهد مشروعاتنا':'View Our Projects','انضم إلى البُنْيَان':'Join BUNYAN',
'مجالات تنموية':'Development Fields','مبادرة مستهدفة':'Target Initiatives','متطوعاً مستهدفاً':'Target Volunteers','مستفيد مستهدف':'Target Beneficiaries','العدالة':'Justice','الاستدامة':'Sustainability',
'برامج بُنْيَان':'BUNYAN Programs','التعليم والمعرفة':'Education and Knowledge','الصحة والمجتمع':'Health and Community','التمكين الاقتصادي':'Economic Empowerment','التحول الرقمي':'Digital Transformation',
'من الفكرة إلى أثر يُرى':'From idea to visible impact','ساهم في المشروع':'Support Project','عرض تفاصيل المشروع':'View Project Details','عرض صفحة المشروع':'View Project Page','الميزانية':'Budget','حالة التنفيذ':'Implementation Status','قيد النشر':'Pending Publication','في مرحلة الإعداد':'Preparation Stage','آخر تحديث: لم يُنشر':'Last update: not published',
'الأثر بالأرقام':'Impact in Numbers','نفصل بين الطموح والنتيجة':'We separate ambition from results','الأهداف المستهدفة':'Target Goals','النتائج الموثقة':'Verified Results','المجالات التنموية':'Development Fields','المبادرات المستهدفة':'Target Initiatives','المتطوعون المستهدفون':'Target Volunteers','المستفيدون المستهدفون':'Target Beneficiaries','المشروعات المكتملة':'Completed Projects','المستفيدون الموثقون':'Verified Beneficiaries','المساهمات المؤكدة':'Verified Contributions','ساعات التطوع':'Volunteer Hours','قيد التوثيق':'Pending Documentation','بعد اعتماد تقارير الفرق':'After team reports are approved',
'الشفافية العامة':'Public Transparency','أين يذهب الدعم؟':'Where does the support go?','إجمالي المساهمات المؤكدة':'Verified Contribution Total','إجمالي المصروفات الموثقة':'Verified Expense Total','الرصيد المتاح للمشروعات':'Available Project Balance','آخر تحديث مالي':'Latest Financial Update','عمليات موثقة':'Verified Transactions','قاعدة بُنْيَان:':'BUNYAN Rule:','جاري التحميل…':'Loading…','جاري التحميل...':'Loading...','جاري تحميل البيانات الموثقة…':'Loading verified data…','لا توجد بيانات':'No data available','تعذر تحميل البيانات الموثقة':'Unable to load verified data',
'آخر الأخبار':'Latest News','نبض بُنْيَان':'BUNYAN Pulse','الدعم يصنع أثراً':'Support creates impact','ساهم في مشروع موثّق':'Support a verified project','تسجيل مساهمة':'Register Contribution','المشاركة تصنع الفرق':'Participation makes a difference','لك مكان في هذا البُنْيَان':'You have a place in BUNYAN','إرسال الطلب':'Send Request','إرسال الرسالة':'Send Message',
'الاسم الكامل':'Full Name','رقم الهاتف':'Phone Number','اسم المساهم':'Contributor Name','المبلغ':'Amount','العملة':'Currency','اسم المشروع':'Project Name','طريقة الدفع':'Payment Method','رقم المرجع':'Reference Number','اختياري':'Optional','حفظ المساهمة':'Save Contribution','كلمة المرور':'Password','البريد الإلكتروني':'Email Address','دخول':'Sign In','إغلاق':'Close','إلغاء':'Cancel','حفظ':'Save','حذف':'Delete','تعديل':'Edit','معاينة':'Preview','فتح':'Open','تنزيل':'Download','طباعة':'Print','مشاركة':'Share','نسخ الرابط':'Copy Link','تم النسخ!':'Copied!',
'نظرة عامة':'Overview','إدارة المشروعات':'Project Management','المستفيدون':'Beneficiaries','المتطوعون':'Volunteers','المساهمات':'Contributions','التبرعات':'Donations','المصروفات':'Expenses','المستندات':'Documents','طلبات المشاركة':'Participation Requests','المركز المالي':'Finance Centre','الشفافية والتقارير':'Transparency & Reports','الإعدادات':'Settings','عرض الموقع':'View Website','تنزيل نسخة احتياطية':'Download Backup','تسجيل الخروج':'Logout','حالة النظام':'System Status','النسخ الاحتياطي والتدقيق':'Backup & Audit',
'مركز إدارة المشروعات':'Project Management Centre','مركز المشروعات والشفافية':'Projects and Transparency Centre','مشروع جديد':'New Project','إنشاء مشروع جديد':'Create New Project','إضافة مشروع':'Add Project','كل المشروعات':'All Projects','المنشورة':'Published','المسودات':'Drafts','النشطة':'Active','المكتملة':'Completed','ابحث باسم المشروع أو الحالة':'Search by project name or status','لا توجد مشروعات بعد. ابدأ بإنشاء أول مشروع.':'No projects yet. Create the first project.','لا توجد صورة للمشروع':'No project image','منشور':'Published','مسودة':'Draft','ظاهر في الموقع':'Visible on website','غير ظاهر للزوار':'Hidden from visitors','الإنجاز':'Progress','المستهدفون':'Target beneficiaries','نسبة الإنجاز':'Progress','عدد المستفيدين المستهدف':'Target Beneficiaries','الملخص التنفيذي':'Executive Summary','رفع صورة المشروع':'Upload Project Image','اختر صورة غلاف للمشروع':'Choose a project cover image','حذف الصورة الحالية':'Remove current image','نشر المشروع في الموقع العام':'Publish project on public website','حفظ التعديلات':'Save Changes','إنشاء المشروع':'Create Project','جاري حفظ بيانات المشروع...':'Saving project data...','جاري رفع صورة المشروع...':'Uploading project image...','تم حفظ المشروع والصورة بنجاح.':'Project and image saved successfully.',
'قيد التخطيط':'Planning','نشط':'Active','متوقف مؤقتاً':'Paused','مكتمل':'Completed','جديد':'New','قيد المراجعة':'Pending Review','موثق':'Verified','موثقة':'Verified','مرفوض':'Rejected','مرفوضة':'Rejected','مقبول':'Accepted','غير نشط':'Inactive','عام':'Public','خاص':'Private',
'إدارة المصروفات والفواتير والمستندات من مكان واحد.':'Manage expenses, invoices and documents in one place.','المصروف':'Spent','المتبقي':'Remaining','المستندات والفواتير':'Documents and Invoices','إضافة مصروف':'Add Expense','رفع مستند أو فاتورة':'Upload Document or Invoice','لا توجد مصروفات حتى الآن.':'No expenses yet.','لا توجد مستندات أو فواتير بعد.':'No documents or invoices yet.','بيان المصروف':'Expense Description','التاريخ':'Date','التصنيف':'Category','ملاحظات':'Notes','إظهار المصروف في صفحة الشفافية':'Show expense on transparency page','حفظ المصروف':'Save Expense','اختر الملف':'Choose File','نوع الملف':'File Type','فاتورة':'Invoice','إيصال':'Receipt','عقد':'Contract','تقرير':'Report','مستند آخر':'Other Document','إظهار الملف للعامة':'Make file public','رفع الملف':'Upload File','المصروفات والمستندات':'Expenses and Documents','الحالة':'Status',
'صفحة المشروع':'Project Page','عن المشروع':'About the Project','آخر التحديثات':'Latest Updates','المصروفات المنشورة':'Published Expenses','بيانات المشروع':'Project Information','الموقع':'Location','تاريخ البداية':'Start Date','تاريخ النهاية':'End Date','المستندات العامة':'Public Documents','الرصيد المتاح':'Available Balance','المساهمات الموثقة':'Verified Contributions','المصروفات الموثقة':'Verified Expenses','ساهم في هذا المشروع':'Support This Project','نسخ رابط المشروع':'Copy Project Link','لا توجد تحديثات منشورة بعد.':'No published updates yet.','لا توجد مصروفات موثقة منشورة بعد.':'No verified public expenses yet.','لا توجد مستندات عامة بعد.':'No public documents yet.','قيد التحديد':'To Be Confirmed','غير مصنف':'Uncategorised',
'خريطة مشروعات بُنْيَان':'BUNYAN Project Map','المشروعات على خريطة السودان':'Projects Across Sudan','استكشف مواقع المشروعات ونسبة إنجازها وافتح الصفحة الكاملة لكل مشروع.':'Explore project locations, progress and full project pages.','لا توجد مشروعات محددة على الخريطة بعد.':'No geolocated projects yet.','تحديد موقع المشروع':'Set Project Location','اسم الموقع':'Location Name','خط العرض':'Latitude','خط الطول':'Longitude','حفظ الموقع':'Save Location','إزالة الموقع من الخريطة':'Remove from Map',
'إعدادات بُنْيَان':'BUNYAN Settings','المظهر واللغة وإعدادات الجهاز.':'Appearance, language and device settings.','الوضع الليلي':'Dark Mode','تشغيل الوضع الليلي':'Enable Dark Mode','إيقاف الوضع الليلي':'Disable Dark Mode','اللغة':'Language','تحديث التطبيق':'App Update','تحديث كامل':'Full Update','التحقق من التحديث':'Check for Update','تصدير CSV':'Export CSV','إجمالي':'Total','صحة النظام':'System Health','قاعدة البيانات':'Database','زمن الاستجابة':'Response Time','الإصدار':'Version','آخر فحص':'Last Check','النظام يعمل':'System Online','بانتظار المراجعة':'Awaiting Review','إشعارات تحويل':'Transfer Notices','إجمالي المبالغ الموثقة':'Verified Amount Totals'
};
const R=Object.fromEntries(Object.entries(D).map(([ar,en])=>[en,ar]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const hasArabic=v=>/[\u0600-\u06FF]/.test(v);
function pattern(v,target){const s=clean(v);let m;if(target==='en'){if((m=s.match(/^(\d+)\s*مشروع(?:اً|ات)?$/)))return `${m[1]} Projects`;if((m=s.match(/^(\d+)\s*سجل$/)))return `${m[1]} Records`;if((m=s.match(/^(\d+)\s*عملية موثقة$/)))return `${m[1]} Verified Transactions`;if((m=s.match(/^الإنجاز\s*(\d+)%$/)))return `Progress ${m[1]}%`;if((m=s.match(/^(\d+)%\s*موثق$/)))return `${m[1]}% Verified`;if((m=s.match(/^آخر تحديث:\s*(.+)$/)))return `Last update: ${m[1]}`;}else{if((m=s.match(/^(\d+)\s*Projects?$/i)))return `${m[1]} مشروع`;if((m=s.match(/^(\d+)\s*Records?$/i)))return `${m[1]} سجل`;if((m=s.match(/^(\d+)\s*Verified Transactions?$/i)))return `${m[1]} عملية موثقة`;if((m=s.match(/^Progress\s*(\d+)%$/i)))return `الإنجاز ${m[1]}%`;if((m=s.match(/^(\d+)%\s*Verified$/i)))return `${m[1]}% موثق`;if((m=s.match(/^Last update:\s*(.+)$/i)))return `آخر تحديث: ${m[1]}`;}return null;}
function translate(v,target){const s=clean(v);if(!s)return v;return (target==='en'?D[s]:R[s])??pattern(s,target)??v;}
function captureText(n){const raw=n.nodeValue;if(!clean(raw))return null;const s=clean(raw);let ar,en;if(D[s]){ar=s;en=D[s]}else if(R[s]){ar=R[s];en=s}else if(hasArabic(s)){ar=s;en=translate(s,'en')}else{en=s;ar=translate(s,'ar')}const rec={ar,en,prefix:(raw.match(/^\s*/)||[''])[0],suffix:(raw.match(/\s*$/)||[''])[0]};textState.set(n,rec);return rec;}
function applyText(n,force=false){if(!n||n.nodeType!==3||/^(SCRIPT|STYLE|TEXTAREA)$/i.test(n.parentElement?.tagName||'')||n.parentElement?.closest?.('[data-no-i18n]'))return;let rec=textState.get(n);if(!rec||force)rec=captureText(n);if(!rec)return;const out=lang==='en'?rec.en:rec.ar;const value=rec.prefix+out+rec.suffix;if(n.nodeValue!==value)n.nodeValue=value;}
function applyAttrs(el,force=false){if(!el?.getAttribute||el.closest?.('[data-no-i18n]'))return;let store=attrState.get(el);if(!store||force){store={};for(const a of ['placeholder','title','aria-label'])if(el.hasAttribute(a)){const v=el.getAttribute(a),s=clean(v);store[a]={ar:D[s]?s:R[s]||s,en:D[s]||s};}attrState.set(el,store)}for(const [a,r] of Object.entries(store)){const value=lang==='en'?r.en:r.ar;if(el.getAttribute(a)!==value)el.setAttribute(a,value)}}
function markToggle(el){if(!el)return;el.dataset.languageToggle='true';if(el.tagName==='BUTTON'&&el.type!=='button')el.type='button';const text=lang==='ar'?'English':'العربية';const label=lang==='ar'?'Switch to English':'التبديل إلى العربية';if(el.textContent!==text)el.textContent=text;if(el.getAttribute('aria-label')!==label)el.setAttribute('aria-label',label);}
function ensureToggle(){let b=document.querySelector('[data-language-toggle="true"],#languageToggle');if(!b){const nav=document.querySelector('#nav');if(nav){b=document.createElement('button');b.id='languageToggle';b.className='outline language-toggle';nav.insertBefore(b,document.querySelector('#adminBtn')||null)}}markToggle(b);document.querySelectorAll('#toggleLang').forEach(markToggle);}
function walk(root=document.body,force=false){if(!root||applying)return;applying=true;try{if(root.nodeType===3)applyText(root,force);else{applyAttrs(root,force);const w=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))n.nodeType===3?applyText(n,force):applyAttrs(n,force)}ensureToggle()}finally{applying=false}}
function direction(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';if(document.body){document.body.dir=document.documentElement.dir;document.body.classList.toggle('lang-ar',lang==='ar');document.body.classList.toggle('lang-en',lang==='en')}document.title=lang==='ar'?'بُنْيَان | مؤسسة شمس الأنبياء للتنمية':'BUNYAN | Shams Al-Anbiya Foundation for Development'}
function setLanguage(next){lang=next==='en'?'en':'ar';localStorage.setItem(KEY,lang);direction();walk(document.body);window.dispatchEvent(new CustomEvent('bunyan:languagechange',{detail:{lang}}));setTimeout(()=>walk(document.body),120);setTimeout(()=>walk(document.body),700)}
document.addEventListener('click',e=>{const el=e.target.closest?.('[data-language-toggle="true"],#toggleLang,#languageToggle');if(!el)return;e.preventDefault();e.stopImmediatePropagation();setLanguage(lang==='ar'?'en':'ar')},true);
function scheduleRefresh(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;walk(document.body,false)});}
const observer=new MutationObserver(records=>{if(applying)return;let needs=false;for(const r of records){if(r.type==='childList'&&r.addedNodes.length){needs=true;break}}if(needs)scheduleRefresh();});
function init(){direction();walk(document.body,true);observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>walk(document.body,false),500);setTimeout(()=>walk(document.body,false),1600)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.BunyanI18n={getLanguage:()=>lang,setLanguage,t:key=>lang==='en'?(D[key]||key):(R[key]||key),refresh:()=>walk(document.body,false),dictionary:D};
})();