(()=>{
'use strict';
const KEY='bunyan_language';
let lang=localStorage.getItem(KEY)==='en'?'en':'ar';
let applying=false,timer=0;
const pairs=[
['بُنْيَان','BUNYAN'],['مؤسسة شمس الأنبياء للتنمية','Shams Al-Anbiya Foundation for Development'],['هنا يُبنى الإنسان','Building people here'],['الإنسان أولاً','People First'],
['من نحن','About Us'],['البرامج','Programs'],['المشروعات','Projects'],['الأخبار','News'],['شارك معنا','Join Us'],['اتصل بنا','Contact Us'],['لوحة الإدارة','Admin Dashboard'],['الأثر','Impact'],['الشفافية','Transparency'],['خريطة الأثر','Impact Map'],
['من المجتمع المحلي إلى أثر مستدام','From local community to sustainable impact'],['نبني الإنسان','We build people'],['ليَبني المستقبل','to build the future'],['شاهد مشروعاتنا','View Our Projects'],['انضم إلى البُنْيَان','Join BUNYAN'],
['مجالات تنموية','Development Fields'],['مبادرة مستهدفة','Target Initiatives'],['متطوعاً مستهدفاً','Target Volunteers'],['مستفيد مستهدف','Target Beneficiaries'],['العدالة','Justice'],['الاستدامة','Sustainability'],
['برامج بُنْيَان','BUNYAN Programs'],['أربعة مسارات لبناء مجتمع أقوى','Four pathways to build a stronger community'],['التعليم والمعرفة','Education and Knowledge'],['الصحة والمجتمع','Health and Community'],['التمكين الاقتصادي','Economic Empowerment'],['التحول الرقمي','Digital Transformation'],
['دعم المدارس، التدريب، والمكتبات الرقمية.','Supporting schools, training and digital libraries.'],['الرعاية الوقائية وصحة الأم والطفل.','Preventive care and maternal and child health.'],['المهارات والمشروعات الصغيرة.','Skills and small enterprises.'],['منصات وبيانات لخدمة التنمية.','Platforms and data serving development.'],
['من الفكرة إلى أثر يُرى','From idea to visible impact'],['ساهم في المشروع','Support Project'],['عرض تفاصيل المشروع','View Project Details'],['عرض صفحة المشروع','View Project Page'],['الميزانية','Budget'],['حالة التنفيذ','Implementation Status'],['قيد النشر','Pending Publication'],['في مرحلة الإعداد','Preparation Stage'],['آخر تحديث: لم يُنشر','Last update: not published'],
['الأثر بالأرقام','Impact in Numbers'],['نفصل بين الطموح والنتيجة','We separate ambition from results'],['الأهداف المستهدفة','Target Goals'],['النتائج الموثقة','Verified Results'],['المشروعات المكتملة','Completed Projects'],['المستفيدون الموثقون','Verified Beneficiaries'],['المساهمات المؤكدة','Verified Contributions'],['ساعات التطوع','Volunteer Hours'],['قيد التوثيق','Pending Documentation'],
['الشفافية العامة','Public Transparency'],['أين يذهب الدعم؟','Where does the support go?'],['إجمالي المساهمات المؤكدة','Verified Contribution Total'],['إجمالي المصروفات الموثقة','Verified Expense Total'],['الرصيد المتاح للمشروعات','Available Project Balance'],['آخر تحديث مالي','Latest Financial Update'],['عمليات موثقة','Verified Transactions'],['قاعدة بُنْيَان:','BUNYAN Rule:'],['جاري التحميل…','Loading…'],['جاري التحميل...','Loading...'],['لا توجد بيانات','No data available'],['تعذر تحميل البيانات الموثقة','Unable to load verified data'],
['آخر الأخبار','Latest News'],['نبض بُنْيَان','BUNYAN Pulse'],['الدعم يصنع أثراً','Support creates impact'],['ساهم في مشروع موثّق','Support a verified project'],['تسجيل مساهمة','Register Contribution'],['المشاركة تصنع الفرق','Participation makes a difference'],['لك مكان في هذا البُنْيَان','You have a place in BUNYAN'],['إرسال الطلب','Send Request'],['إرسال الرسالة','Send Message'],
['الاسم الكامل','Full Name'],['رقم الهاتف','Phone Number'],['اسم المساهم','Contributor Name'],['المبلغ','Amount'],['العملة','Currency'],['اسم المشروع','Project Name'],['طريقة الدفع','Payment Method'],['رقم المرجع','Reference Number'],['اختياري','Optional'],['حفظ المساهمة','Save Contribution'],['كلمة المرور','Password'],['البريد الإلكتروني','Email Address'],['دخول','Sign In'],['إغلاق','Close'],['إلغاء','Cancel'],['حفظ','Save'],['حذف','Delete'],['تعديل','Edit'],['معاينة','Preview'],['فتح','Open'],['تنزيل','Download'],['طباعة','Print'],['مشاركة','Share'],['نسخ الرابط','Copy Link'],['تم النسخ!','Copied!'],
['نظرة عامة','Overview'],['إدارة المشروعات','Project Management'],['المستفيدون','Beneficiaries'],['المتطوعون','Volunteers'],['المساهمات','Contributions'],['التبرعات','Donations'],['المصروفات','Expenses'],['المستندات','Documents'],['طلبات المشاركة','Participation Requests'],['المركز المالي','Finance Centre'],['الشفافية والتقارير','Transparency & Reports'],['الإعدادات','Settings'],['عرض الموقع','View Website'],['تنزيل نسخة احتياطية','Download Backup'],['تسجيل الخروج','Logout'],['حالة النظام','System Status'],['النسخ الاحتياطي والتدقيق','Backup & Audit'],
['مشروع جديد','New Project'],['إنشاء مشروع جديد','Create New Project'],['إضافة مشروع','Add Project'],['كل المشروعات','All Projects'],['المنشورة','Published'],['المسودات','Drafts'],['النشطة','Active'],['المكتملة','Completed'],['منشور','Published'],['مسودة','Draft'],['الإنجاز','Progress'],['المستهدفون','Target beneficiaries'],['نسبة الإنجاز','Progress'],['الملخص التنفيذي','Executive Summary'],['رفع صورة المشروع','Upload Project Image'],['حفظ التعديلات','Save Changes'],['إنشاء المشروع','Create Project'],
['قيد التخطيط','Planning'],['نشط','Active'],['متوقف مؤقتاً','Paused'],['مكتمل','Completed'],['جديد','New'],['قيد المراجعة','Pending Review'],['موثق','Verified'],['موثقة','Verified'],['مرفوض','Rejected'],['مرفوضة','Rejected'],['مقبول','Accepted'],['غير نشط','Inactive'],['عام','Public'],['خاص','Private'],
['المصروف','Spent'],['المتبقي','Remaining'],['المستندات والفواتير','Documents and Invoices'],['إضافة مصروف','Add Expense'],['رفع مستند أو فاتورة','Upload Document or Invoice'],['بيان المصروف','Expense Description'],['التاريخ','Date'],['التصنيف','Category'],['ملاحظات','Notes'],['حفظ المصروف','Save Expense'],['اختر الملف','Choose File'],['نوع الملف','File Type'],['فاتورة','Invoice'],['إيصال','Receipt'],['عقد','Contract'],['تقرير','Report'],['مستند آخر','Other Document'],['رفع الملف','Upload File'],['الحالة','Status'],
['صفحة المشروع','Project Page'],['عن المشروع','About the Project'],['آخر التحديثات','Latest Updates'],['المصروفات المنشورة','Published Expenses'],['بيانات المشروع','Project Information'],['الموقع','Location'],['تاريخ البداية','Start Date'],['تاريخ النهاية','End Date'],['المستندات العامة','Public Documents'],['الرصيد المتاح','Available Balance'],['المساهمات الموثقة','Verified Contributions'],['المصروفات الموثقة','Verified Expenses'],['ساهم في هذا المشروع','Support This Project'],['نسخ رابط المشروع','Copy Project Link'],['قيد التحديد','To Be Confirmed'],['غير مصنف','Uncategorised'],
['خريطة مشروعات بُنْيَان','BUNYAN Project Map'],['المشروعات على خريطة السودان','Projects Across Sudan'],['تحديد موقع المشروع','Set Project Location'],['اسم الموقع','Location Name'],['خط العرض','Latitude'],['خط الطول','Longitude'],['حفظ الموقع','Save Location'],['إزالة الموقع من الخريطة','Remove from Map'],
['إعدادات بُنْيَان','BUNYAN Settings'],['المظهر واللغة وإعدادات الجهاز.','Appearance, language and device settings.'],['الوضع الليلي','Dark Mode'],['تشغيل الوضع الليلي','Enable Dark Mode'],['إيقاف الوضع الليلي','Disable Dark Mode'],['اللغة','Language'],['تحديث التطبيق','App Update'],['تحديث كامل','Full Update'],['التحقق من التحديث','Check for Update'],['تصدير CSV','Export CSV'],['إجمالي','Total'],['صحة النظام','System Health'],['قاعدة البيانات','Database'],['زمن الاستجابة','Response Time'],['الإصدار','Version'],['آخر فحص','Last Check'],['النظام يعمل','System Online']
];
const AR=new Map(pairs),EN=new Map(pairs.map(([a,e])=>[e,a]));
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function dynamic(s,target){let m;if(target==='en'){
 if((m=s.match(/^(\d+)\s*مشروع(?:اً|ات)?$/)))return `${m[1]} Projects`;
 if((m=s.match(/^(\d+)\s*سجل$/)))return `${m[1]} Records`;
 if((m=s.match(/^الإنجاز\s*(\d+)%$/)))return `Progress ${m[1]}%`;
 if((m=s.match(/^آخر تحديث:\s*(.+)$/)))return `Last update: ${m[1]}`;
}else{
 if((m=s.match(/^(\d+)\s*Projects?$/i)))return `${m[1]} مشروع`;
 if((m=s.match(/^(\d+)\s*Records?$/i)))return `${m[1]} سجل`;
 if((m=s.match(/^Progress\s*(\d+)%$/i)))return `الإنجاز ${m[1]}%`;
 if((m=s.match(/^Last update:\s*(.+)$/i)))return `آخر تحديث: ${m[1]}`;
}return null;}
function convert(s,target){s=clean(s);if(!s)return s;return target==='en'?(AR.get(s)||dynamic(s,'en')||s):(EN.get(s)||dynamic(s,'ar')||s);}
function translateNode(n){if(n.nodeType!==Node.TEXT_NODE||!clean(n.nodeValue)||/^(SCRIPT|STYLE|TEXTAREA)$/i.test(n.parentElement?.tagName||'')||n.parentElement?.closest?.('[data-no-i18n]'))return;const raw=n.nodeValue,prefix=(raw.match(/^\s*/)||[''])[0],suffix=(raw.match(/\s*$/)||[''])[0];n.nodeValue=prefix+convert(raw,lang)+suffix;}
function translateElement(el){if(!el?.getAttribute||el.closest?.('[data-no-i18n]'))return;for(const a of ['placeholder','title','aria-label'])if(el.hasAttribute(a))el.setAttribute(a,convert(el.getAttribute(a),lang));}
function paint(root=document.body){if(!root||applying)return;applying=true;try{
 if(root.nodeType===Node.TEXT_NODE)translateNode(root);else{
  translateElement(root);const w=document.createTreeWalker(root,NodeFilter.SHOW_ELEMENT|NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode()))n.nodeType===Node.TEXT_NODE?translateNode(n):translateElement(n);
 }
 const label=lang==='ar'?'English':'العربية';document.querySelectorAll('[data-language-toggle="true"],#languageToggle,#toggleLang').forEach(b=>{if(b.textContent!==label)b.textContent=label;b.disabled=false;b.removeAttribute('disabled');b.style.opacity='1';b.style.pointerEvents='auto';});
}finally{applying=false;}}
function direction(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.body?.setAttribute('dir',document.documentElement.dir);document.body?.classList.toggle('lang-ar',lang==='ar');document.body?.classList.toggle('lang-en',lang==='en');document.title=lang==='ar'?'بُنْيَان | مؤسسة شمس الأنبياء للتنمية':'BUNYAN | Shams Al-Anbiya Foundation for Development';}
function setLanguage(next){lang=next==='en'?'en':'ar';localStorage.setItem(KEY,lang);direction();paint(document.body);setTimeout(()=>paint(document.body),80);setTimeout(()=>paint(document.body),500);window.dispatchEvent(new CustomEvent('bunyan:languagechange',{detail:{lang}}));}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-language-toggle="true"],#languageToggle,#toggleLang');if(!b)return;e.preventDefault();e.stopImmediatePropagation();setLanguage(lang==='ar'?'en':'ar');},true);
const observer=new MutationObserver(records=>{if(applying)return;clearTimeout(timer);timer=setTimeout(()=>{for(const r of records)for(const n of r.addedNodes)paint(n);},30);});
function init(){direction();paint(document.body);observer.observe(document.documentElement,{childList:true,subtree:true});setTimeout(()=>paint(document.body),300);setTimeout(()=>paint(document.body),1200);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
window.BunyanI18n={getLanguage:()=>lang,setLanguage,t:key=>convert(key,lang),refresh:()=>paint(document.body),dictionary:Object.fromEntries(pairs)};
})();