(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const origins=window.BUNYAN_API_ORIGINS||[window.BUNYAN_API_ORIGIN||'https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
let origin=sessionStorage.getItem('bunyan_api_origin')||origins[0],mode='news',rows=[],projects=[];
const token=()=>sessionStorage.getItem('bunyan_token')||'';
async function api(path,options={}){const headers={...(options.headers||{})};if(token())headers.Authorization=`Bearer ${token()}`;if(options.body&&!(options.body instanceof FormData)){headers['Content-Type']='application/json';if(typeof options.body==='object')options.body=JSON.stringify(options.body)}let last;for(const base of [origin,...origins.filter(x=>x!==origin)]){try{const res=await fetch(base+path,{...options,headers,cache:'no-store'}),text=await res.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!res.ok){const e=new Error(data.error||data.message||`فشل الطلب (${res.status})`);e.status=res.status;throw e}origin=base;sessionStorage.setItem('bunyan_api_origin',base);return data}catch(e){last=e;if(e.status&&e.status>=400&&e.status<500&&![401,403].includes(e.status))throw e}}throw last||new Error('تعذر الاتصال بالخادم')}
const fmt=d=>d?new Date(d).toLocaleString('ar-SD'):'غير منشور';
const live=x=>Boolean(x.is_public&&x.published_at);
function card(x){const project=projects.find(p=>String(p.id)===String(x.project_id));return `<article class="nv7-card" data-search="${esc(`${x.title||''} ${x.body||''} ${project?.name||''}`.toLowerCase())}" data-state="${live(x)?'live':'draft'}"><div class="nv7-row"><div><span class="nv7-badge ${live(x)?'live':'draft'}">${live(x)?'منشور':'مسودة'}</span><h4>${esc(x.title||'بلا عنوان')}</h4></div><small>${fmt(x.published_at||x.created_at)}</small></div><p>${esc(x.body||'')}</p><div class="nv7-meta">${mode==='updates'?`<span>المشروع: <b>${esc(project?.name||'غير محدد')}</b></span>`:''}<span>رقم السجل: ${esc(x.id)}</span></div><div class="nv7-actions"><button data-edit="${x.id}">تعديل</button><button data-toggle="${x.id}">${live(x)?'إلغاء النشر':'نشر الآن'}</button><button class="danger" data-delete="${x.id}">حذف</button></div></article>`}
async function load(){const content=$('#dashContent'),title=$('#dashTitle');if(!content)return;if(title)title.textContent='الأخبار والتحديثات';content.innerHTML='<div class="loading">جاري تحميل الأخبار...</div>';try{projects=await api('/api/projects');rows=await api(mode==='news'?'/api/news':'/api/updates');render()}catch(e){content.innerHTML=`<div class="error-msg">${esc(e.message)}</div>`}}
function render(){const content=$('#dashContent');const published=rows.filter(live).length,drafts=rows.length-published,today=rows.filter(x=>x.created_at&&new Date(x.created_at).toDateString()===new Date().toDateString()).length;content.innerHTML=`<section class="nv7-head"><div><span>المرحلة السابعة</span><h3>الأخبار والتحديثات</h3><p>إدارة النشر المؤسسي وتحديثات المشروعات من مكان واحد.</p></div><button id="nv7Add" class="primary">+ ${mode==='news'?'خبر جديد':'تحديث مشروع'}</button></section><div class="nv7-kpis"><article class="nv7-kpi"><span>إجمالي السجلات</span><strong>${rows.length}</strong></article><article class="nv7-kpi"><span>المنشورة</span><strong>${published}</strong></article><article class="nv7-kpi"><span>المسودات</span><strong>${drafts}</strong></article><article class="nv7-kpi"><span>أضيفت اليوم</span><strong>${today}</strong></article></div><div class="nv7-tabs"><button data-tab="news" class="${mode==='news'?'active':''}">الأخبار</button><button data-tab="updates" class="${mode==='updates'?'active':''}">تحديثات المشروعات</button></div><div class="nv7-tools"><input id="nv7Search" placeholder="ابحث في العنوان أو المحتوى"><select id="nv7Filter"><option value="all">الكل</option><option value="live">المنشورة</option><option value="draft">المسودات</option></select><span class="count-badge">${rows.length} سجل</span></div><div class="nv7-list">${rows.length?rows.map(card).join(''):'<div class="nv7-empty">لا توجد بيانات بعد.</div>'}</div>`;$('#nv7Add').onclick=()=>editor();$$('[data-tab]').forEach(b=>b.onclick=()=>{mode=b.dataset.tab;load()});$('#nv7Search').oninput=filter;$('#nv7Filter').onchange=filter;$$('[data-edit]').forEach(b=>b.onclick=()=>editor(rows.find(x=>String(x.id)===b.dataset.edit)));$$('[data-toggle]').forEach(b=>b.onclick=()=>toggle(rows.find(x=>String(x.id)===b.dataset.toggle)));$$('[data-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.delete))}
function filter(){const q=$('#nv7Search')?.value.trim().toLowerCase()||'',f=$('#nv7Filter')?.value||'all';$$('.nv7-card').forEach(c=>c.hidden=!((!q||c.dataset.search.includes(q))&&(f==='all'||c.dataset.state===f)))}
function editor(item={}){$('.nv7-modal')?.remove();const m=document.createElement('div');m.className='nv7-modal';m.innerHTML=`<form class="nv7-form"><button type="button" class="nv7-close">×</button><h2>${item.id?'تعديل':'إضافة'} ${mode==='news'?'خبر':'تحديث مشروع'}</h2>${mode==='updates'?`<label>المشروع<select name="project_id" required><option value="">اختر المشروع</option>${projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></label>`:''}<label>العنوان<input name="title" value="${esc(item.title||'')}" minlength="3" maxlength="220" required></label><label>المحتوى<textarea name="body" rows="8" minlength="10" maxlength="8000" required>${esc(item.body||'')}</textarea></label><div class="nv7-two"><label>تاريخ النشر<input type="datetime-local" name="published_at" value="${item.published_at?new Date(item.published_at).toISOString().slice(0,16):''}"></label><label class="nv7-check"><input type="checkbox" name="is_public" ${item.is_public?'checked':''}> نشر للزوار</label></div><div class="nv7-submit"><button type="button" class="nv7-cancel">إلغاء</button><button class="primary" type="submit">حفظ</button></div><small class="nv7-msg"></small></form>`;document.body.appendChild(m);if(mode==='updates'&&item.project_id)m.querySelector('[name=project_id]').value=item.project_id;const close=()=>m.remove();m.querySelector('.nv7-close').onclick=close;m.querySelector('.nv7-cancel').onclick=close;m.onclick=e=>{if(e.target===m)close()};m.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,fd=new FormData(f),msg=f.querySelector('.nv7-msg'),btn=f.querySelector('[type=submit]');const body={title:fd.get('title'),body:fd.get('body'),published_at:fd.get('published_at')?new Date(fd.get('published_at')).toISOString():null,is_public:f.elements.is_public.checked};if(body.is_public&&!body.published_at)body.published_at=new Date().toISOString();if(mode==='updates')body.project_id=fd.get('project_id');try{btn.disabled=true;msg.textContent='جاري الحفظ...';const path=mode==='news'?'/api/news':'/api/updates';await api(item.id?`${path}/${item.id}`:path,{method:item.id?'PATCH':'POST',body});close();load();window.loadPublic?.()}catch(x){msg.textContent=x.message}finally{btn.disabled=false}}}
async function toggle(x){const path=mode==='news'?'/api/news':'/api/updates';const next=!live(x);try{await api(`${path}/${x.id}`,{method:'PATCH',body:{is_public:next,published_at:next?(x.published_at||new Date().toISOString()):null}});load();window.loadPublic?.()}catch(e){alert(e.message)}}
async function remove(id){if(!confirm('حذف هذا السجل نهائيًا؟'))return;const path=mode==='news'?'/api/news':'/api/updates';try{await api(`${path}/${id}`,{method:'DELETE'});load();window.loadPublic?.()}catch(e){alert(e.message)}}
function install(){const news=$('[data-view="news"]');if(news)news.addEventListener('click',e=>{e.preventDefault();mode='news';load()},true);window.openNewsCenter=load}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();