(()=>{
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const origins=window.BUNYAN_API_ORIGINS||[window.BUNYAN_API_ORIGIN||'https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
  const lang=()=>window.BunyanI18n?.getLanguage?.()||localStorage.getItem('bunyan_language')||'ar';
  const t=(ar,en)=>lang()==='en'?en:ar;
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  async function api(path){let last;for(const base of origins){try{const r=await fetch(base+path,{cache:'no-store'}),x=await r.text();let d={};try{d=x?JSON.parse(x):{}}catch{d={message:x}}if(!r.ok)throw new Error(d.error||d.message||`Request failed (${r.status})`);return d}catch(e){last=e}}throw last||new Error('Unable to connect')}
  function loadLeaflet(){if(window.L)return Promise.resolve();return new Promise((resolve,reject)=>{if(!document.querySelector('link[data-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.leaflet='1';document.head.appendChild(l)}const existing=document.querySelector('script[data-leaflet]');if(existing){existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.dataset.leaflet='1';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
  function build(){if($('#projectMapSection'))return;const projects=$('#projects');if(!projects)return;const section=document.createElement('section');section.id='projectMapSection';section.className='bunyan-map-section';section.innerHTML=`<div class="bunyan-map-head"><div><span class="tag dark">${t('خريطة الأثر','Impact map')}</span><h2>${t('مشروعات بُنْيَان على أرض السودان','BUNYAN projects across Sudan')}</h2></div><p>${t('تعرض الخريطة المواقع المعتمدة للمشروعات وحالتها ونسبة إنجازها، دون نشر أي بيانات شخصية للمستفيدين.','The map shows verified project locations, status and progress without exposing beneficiary personal data.')}</p></div><div class="bunyan-map-wrap"><div id="bunyanMap" class="bunyan-map"></div><div id="bunyanMapList" class="bunyan-map-list"><div class="bunyan-map-empty">${t('جاري تحميل المواقع...','Loading project locations...')}</div></div></div>`;projects.after(section);render()}
  async function render(){const mapNode=$('#bunyanMap'),list=$('#bunyanMapList');if(!mapNode||!list)return;try{const [rows]=await Promise.all([api('/api/public/projects'),loadLeaflet()]);const geo=(Array.isArray(rows)?rows:[]).filter(p=>Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude)));if(!geo.length){list.innerHTML=`<div class="bunyan-map-empty">${t('لم تُحدد مواقع المشروعات بعد. يمكن إضافتها من لوحة الإدارة.','Project locations have not been set yet. Add them from the admin dashboard.')}</div>`;mapNode.innerHTML='';return}mapNode.innerHTML='';const map=L.map(mapNode,{scrollWheelZoom:false}).setView([15.6,30.2],5);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'&copy; OpenStreetMap'}).addTo(map);const bounds=[];const markers=[];geo.forEach(p=>{const lat=Number(p.latitude),lng=Number(p.longitude),progress=Math.max(0,Math.min(100,Number(p.progress||0))),marker=L.marker([lat,lng]).addTo(map);bounds.push([lat,lng]);marker.bindPopup(`<div class="bunyan-map-popup"><h3>${esc(p.name)}</h3><div>${t('الإنجاز','Progress')}: <b>${progress}%</b></div><div>${esc(p.location||'')}</div><button data-map-project="${esc(p.slug||'')}">${t('فتح المشروع','Open project')}</button></div>`);marker.on('popupopen',()=>{$$('[data-map-project]').forEach(b=>b.onclick=()=>window.openPublicProject?.(b.dataset.mapProject))});markers.push(marker)});if(bounds.length>1)map.fitBounds(bounds,{padding:[30,30]});else map.setView(bounds[0],9);list.innerHTML=geo.map((p,i)=>`<article class="bunyan-map-item" data-map-index="${i}"><h3>${esc(p.name)}</h3><p>${esc(p.location||t('الموقع محدد على الخريطة','Location marked on map'))}</p><small>${t('الإنجاز','Progress')} ${Math.max(0,Math.min(100,Number(p.progress||0)))}%</small></article>`).join('');$$('[data-map-index]',list).forEach(el=>el.onclick=()=>{const i=Number(el.dataset.mapIndex),m=markers[i];if(m){map.setView(m.getLatLng(),10);m.openPopup()}});setTimeout(()=>map.invalidateSize(),100)}catch(e){list.innerHTML=`<div class="bunyan-map-empty">${t('تعذر تحميل الخريطة الآن.','Unable to load the map right now.')}</div>`}}
  const init=()=>build();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.addEventListener('bunyan:languagechange',()=>{document.querySelector('#projectMapSection')?.remove();build()});window.refreshBunyanMap=render;
})();