const A_ORIGINS=['https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
const A_TOKEN='bunyan_v2_token',A_ORIGIN='bunyan_v2_origin';
const a$=s=>document.querySelector(s),aEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let auditRows=[];
async function aApi(path){const token=sessionStorage.getItem(A_TOKEN)||'',preferred=sessionStorage.getItem(A_ORIGIN)||A_ORIGINS[0];let lastError;for(const origin of [preferred,...A_ORIGINS.filter(x=>x!==preferred)]){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(origin+path,{headers:{Authorization:`Bearer ${token}`},cache:'no-store',signal:controller.signal}),text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok){const e=new Error(data.error||`فشل الطلب (${r.status})`);e.status=r.status;throw e}sessionStorage.setItem(A_ORIGIN,origin);return data}catch(e){lastError=e;if(e.status&&e.status<500)break}finally{clearTimeout(timer)}}throw lastError||new Error('تعذر الاتصال بالخادم')}
function summarize(rows,key){const m=new Map();for(const r of rows){const k=String(r[key]||'غير محدد');m.set(k,(m.get(k)||0)+1)}return [...m.entries()].sort((a,b)=>b[1]-a[1])}
function renderAudit(){const byAction=summarize(auditRows,'action'),byType=summarize(auditRows,'entity_type'),today=new Date().toISOString().slice(0,10),todayCount=auditRows.filter(x=>String(x.created_at||'').startsWith(today)).length;a$('#content').innerHTML=`<section class="audit-workspace"><div class="audit-head"><div><h3>سجل النشاط</h3><p>ملخص آمن للعمليات الإدارية داخل بُنْيَان.</p></div><span>${auditRows.length} حدث</span></div><div class="audit-summary"><article><span>إجمالي الأحداث</span><strong>${auditRows.length}</strong></article><article><span>أحداث اليوم</span><strong>${todayCount}</strong></article><article><span>أنواع العمليات</span><strong>${byAction.length}</strong></article></div><div class="audit-list"><article class="audit-card"><header><h4>حسب الإجراء</h4></header><div class="audit-grid">${byAction.map(([k,v])=>`<div class="audit-field"><span>${aEsc(k)}</span><strong>${v}</strong></div>`).join('')}</div></article><article class="audit-card"><header><h4>حسب نوع الكيان</h4></header><div class="audit-grid">${byType.map(([k,v])=>`<div class="audit-field"><span>${aEsc(k)}</span><strong>${v}</strong></div>`).join('')}</div></article></div></section>`}
async function openAudit(){a$('#pageTitle').textContent='سجل النشاط';document.querySelectorAll('#adminNav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='audit'));a$('#sidebar').classList.remove('open');a$('#backdrop').classList.remove('show');a$('#backdrop').hidden=true;a$('#content').innerHTML='<div class="loading">جاري تحميل سجل النشاط...</div>';try{const me=await aApi('/api/auth/me');if(!['admin','manager'].includes(me?.role)){a$('#content').innerHTML='<div class="error">سجل النشاط متاح للمدير ومدير النظام فقط.</div>';return}const data=await aApi('/api/audit-logs');auditRows=Array.isArray(data)?data:[];renderAudit()}catch(e){if(e.status===401){sessionStorage.removeItem(A_TOKEN);location.reload();return}a$('#content').innerHTML=`<div class="error">${aEsc(e.message)}</div>`}}
document.addEventListener('click',async e=>{const nav=e.target.closest('#adminNav [data-view="audit"]');if(nav){e.preventDefault();e.stopImmediatePropagation();await openAudit()}},true);
(async()=>{try{const me=await aApi('/api/auth/me');const nav=document.querySelector('#adminNav [data-view="audit"]');if(nav&&!['admin','manager'].includes(me?.role))nav.hidden=true}catch{}})();
