const B_ORIGINS=['https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
const B_TOKEN='bunyan_v2_token',B_ORIGIN='bunyan_v2_origin';
const b$=s=>document.querySelector(s),bEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let beneficiaryRows=[],beneficiaryProjects=[],beneficiaryFilter='all',beneficiarySearch='';
async function bApi(path,options={}){const token=sessionStorage.getItem(B_TOKEN)||'',preferred=sessionStorage.getItem(B_ORIGIN)||B_ORIGINS[0],headers={...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;if(options.body){headers['Content-Type']='application/json';options={...options,body:typeof options.body==='string'?options.body:JSON.stringify(options.body)}}let last;for(const origin of [preferred,...B_ORIGINS.filter(x=>x!==preferred)]){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch(origin+path,{...options,headers,cache:'no-store',signal:controller.signal}),text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok){const e=new Error(data.error||`فشل الطلب (${r.status})`);e.status=r.status;throw e}sessionStorage.setItem(B_ORIGIN,origin);return data}catch(e){last=e;if(e.status&&e.status<500)break}finally{clearTimeout(timer)}}throw last||new Error('تعذر الاتصال بالخادم')}
const bStatuses=['جديد','قيد المتابعة','مستفيد','مكتمل','متوقف'];
function bProjectName(id){return beneficiaryProjects.find(p=>String(p.id)===String(id))?.name||'غير مرتبط'}
function bFiltered(){const q=beneficiarySearch.trim().toLowerCase();return beneficiaryRows.filter(r=>(beneficiaryFilter==='all'||String(r.status||'جديد')===beneficiaryFilter)&&(!q||[r.name,r.phone,r.service,r.notes,bProjectName(r.project_id)].some(v=>String(v||'').toLowerCase().includes(q))))}
function bRender(){const list=bFiltered();b$('#content').innerHTML=`<section class="beneficiary-workspace"><div class="section-head"><div><h3>المستفيدون</h3><p>إدارة المستفيدين وربطهم بالمشروعات والخدمات.</p></div><button class="primary" data-beneficiary-new>+ مستفيد جديد</button></div><div class="beneficiary-tools"><input data-beneficiary-search value="${bEsc(beneficiarySearch)}" placeholder="بحث بالاسم أو الهاتف أو الخدمة"><select data-beneficiary-filter><option value="all">كل الحالات (${beneficiaryRows.length})</option>${bStatuses.map(s=>`<option value="${bEsc(s)}" ${beneficiaryFilter===s?'selected':''}>${bEsc(s)} (${beneficiaryRows.filter(x=>(x.status||'جديد')===s).length})</option>`).join('')}</select></div>${list.length?`<div class="beneficiary-list">${list.map(r=>`<article class="beneficiary-card" data-beneficiary-id="${bEsc(r.id)}"><header><div><h4>${bEsc(r.name||'بدون اسم')}</h4><span>${bEsc(r.service||'خدمة غير محددة')}</span></div><strong>${bEsc(r.status||'جديد')}</strong></header><div class="beneficiary-grid"><div><span>الهاتف</span><b>${bEsc(r.phone||'—')}</b></div><div><span>المشروع</span><b>${bEsc(bProjectName(r.project_id))}</b></div><div class="wide"><span>الملاحظات</span><b>${bEsc(r.notes||'—')}</b></div></div><footer>${r.phone?`<a class="ghost compact" href="tel:${bEsc(String(r.phone).replace(/[^+\d]/g,''))}">اتصال</a>`:''}<button class="ghost compact" data-beneficiary-edit>تعديل</button></footer></article>`).join('')}</div>`:'<div class="empty">لا توجد سجلات مطابقة.</div>'}<div id="beneficiaryModal" class="beneficiary-modal" hidden></div></section>`}
function bForm(row={}){const modal=b$('#beneficiaryModal');modal.hidden=false;modal.innerHTML=`<form class="beneficiary-form" data-beneficiary-form data-id="${bEsc(row.id||'')}"><header><h3>${row.id?'تعديل مستفيد':'إضافة مستفيد'}</h3><button type="button" class="ghost compact" data-beneficiary-close>×</button></header><label>الاسم الكامل<input name="name" value="${bEsc(row.name||'')}" required minlength="2"></label><label>رقم الهاتف<input name="phone" value="${bEsc(row.phone||'')}"></label><label>الخدمة<input name="service" value="${bEsc(row.service||'')}"></label><label>الحالة<select name="status">${bStatuses.map(s=>`<option ${String(row.status||'جديد')===s?'selected':''}>${bEsc(s)}</option>`).join('')}</select></label><label>المشروع<select name="project_id"><option value="">غير مرتبط</option>${beneficiaryProjects.map(p=>`<option value="${bEsc(p.id)}" ${String(row.project_id||'')===String(p.id)?'selected':''}>${bEsc(p.name)}</option>`).join('')}</select></label><label class="wide">الملاحظات<textarea name="notes" rows="4">${bEsc(row.notes||'')}</textarea></label><footer><button type="button" class="ghost" data-beneficiary-close>إلغاء</button><button class="primary" type="submit">حفظ</button><span class="inline-message" role="status"></span></footer></form>`}
async function openBeneficiaries(){b$('#pageTitle').textContent='المستفيدون';document.querySelectorAll('#adminNav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='beneficiaries'));b$('#sidebar').classList.remove('open');b$('#backdrop').classList.remove('show');b$('#backdrop').hidden=true;b$('#content').innerHTML='<div class="loading">جاري تحميل المستفيدين...</div>';try{const [rows,backup]=await Promise.all([bApi('/api/beneficiaries'),bApi('/api/backup/export')]);beneficiaryRows=Array.isArray(rows)?rows:[];beneficiaryProjects=Array.isArray(backup?.data?.projects)?backup.data.projects:[];bRender()}catch(e){if(e.status===401){sessionStorage.removeItem(B_TOKEN);location.reload();return}b$('#content').innerHTML=`<div class="error">${bEsc(e.message)}</div><button class="ghost" data-beneficiary-retry>إعادة المحاولة</button>`}}
document.addEventListener('click',async e=>{const nav=e.target.closest('#adminNav [data-view="beneficiaries"]');if(nav){e.preventDefault();e.stopImmediatePropagation();await openBeneficiaries();return}if(e.target.closest('[data-beneficiary-new]')){bForm();return}if(e.target.closest('[data-beneficiary-close]')){b$('#beneficiaryModal').hidden=true;return}if(e.target.closest('[data-beneficiary-retry]')){await openBeneficiaries();return}const edit=e.target.closest('[data-beneficiary-edit]');if(edit){const id=edit.closest('[data-beneficiary-id]').dataset.beneficiaryId;bForm(beneficiaryRows.find(x=>String(x.id)===String(id))||{});return}},true);
document.addEventListener('input',e=>{if(e.target.matches('[data-beneficiary-search]')){beneficiarySearch=e.target.value;bRender()}},true);
document.addEventListener('change',e=>{if(e.target.matches('[data-beneficiary-filter]')){beneficiaryFilter=e.target.value;bRender()}},true);
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-beneficiary-form]');if(!form)return;e.preventDefault();e.stopImmediatePropagation();const msg=form.querySelector('.inline-message'),button=form.querySelector('button[type="submit"]'),fd=new FormData(form),body=Object.fromEntries(fd);if(!body.project_id)body.project_id=null;try{button.disabled=true;msg.textContent='جاري الحفظ...';const id=form.dataset.id;await bApi(id?`/api/beneficiaries/${id}`:'/api/beneficiaries',{method:id?'PATCH':'POST',body});b$('#beneficiaryModal').hidden=true;await openBeneficiaries()}catch(err){msg.textContent=err.message;button.disabled=false}},true);
