const U_ORIGINS=['https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
const U_TOKEN='bunyan_v2_token',U_ORIGIN='bunyan_v2_origin';
const u$=s=>document.querySelector(s),uEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const roleLabels={admin:'مدير النظام',manager:'مدير',staff:'موظف',viewer:'مشاهد فقط'};
let usersRows=[],currentUser=null,userFilter='all';
async function uApi(path,options={}){const token=sessionStorage.getItem(U_TOKEN)||'',preferred=sessionStorage.getItem(U_ORIGIN)||U_ORIGINS[0],headers={...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;if(options.body){headers['Content-Type']='application/json';options={...options,body:typeof options.body==='string'?options.body:JSON.stringify(options.body)}}let lastError;for(const origin of [preferred,...U_ORIGINS.filter(x=>x!==preferred)]){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(origin+path,{...options,headers,cache:'no-store',signal:controller.signal}),text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok){const e=new Error(data.error||`فشل الطلب (${r.status})`);e.status=r.status;throw e}sessionStorage.setItem(U_ORIGIN,origin);return data}catch(e){lastError=e;if(e.status&&e.status<500)break}finally{clearTimeout(timer)}}throw lastError||new Error('تعذر الاتصال بالخادم')}
const uDate=v=>v?new Date(v).toLocaleString('ar-SD',{dateStyle:'medium',timeStyle:'short'}):'—';
function renderCreateForm(){return `<form class="users-form" data-user-form><h4>إنشاء مستخدم جديد</h4><label>الاسم<input name="name" minlength="2" maxlength="160" required></label><label>البريد الإلكتروني<input name="email" type="email" required></label><label>كلمة المرور<input name="password" type="password" minlength="10" maxlength="128" required></label><label>الدور<select name="role"><option value="staff">موظف</option><option value="manager">مدير</option><option value="viewer">مشاهد فقط</option><option value="admin">مدير النظام</option></select></label><div class="form-actions"><button class="primary" type="submit">إنشاء الحساب</button><span class="inline-message" role="status"></span></div></form>`}
function filteredUsers(){if(userFilter==='all')return usersRows;if(userFilter==='active')return usersRows.filter(x=>x.is_active);if(userFilter==='inactive')return usersRows.filter(x=>!x.is_active);return usersRows.filter(x=>x.role===userFilter)}
function renderUsers(){const list=filteredUsers(),active=usersRows.filter(x=>x.is_active).length,admins=usersRows.filter(x=>x.role==='admin'&&x.is_active).length;u$('#content').innerHTML=`<section class="users-workspace"><div class="users-head"><div><h3>المستخدمون والصلاحيات</h3><p>إدارة حسابات فريق بُنْيَان وأدوار الوصول.</p></div><button class="primary" data-user-new>مستخدم جديد</button></div><div class="users-summary"><article><span>إجمالي الحسابات</span><strong>${usersRows.length}</strong></article><article><span>الحسابات النشطة</span><strong>${active}</strong></article><article><span>مديرو النظام النشطون</span><strong>${admins}</strong></article></div><div class="users-filters">${[['all','الكل'],['active','نشط'],['inactive','متوقف'],['admin','مديرو النظام'],['manager','المديرون'],['staff','الموظفون'],['viewer','المشاهدون']].map(([v,l])=>`<button data-user-filter="${v}" class="${userFilter===v?'active':''}">${l}</button>`).join('')}</div><div data-user-form-slot></div>${list.length?`<div class="users-list">${list.map(row=>{const self=currentUser&&row.id===currentUser.id;return `<article class="user-card" data-user-id="${uEsc(row.id)}"><header><div><h4>${uEsc(row.name)}</h4><div class="email">${uEsc(row.email)}</div></div><span class="user-status ${row.is_active?'user-active':'user-inactive'}">${row.is_active?'نشط':'متوقف'}</span></header><div class="user-grid"><div class="user-field"><span>الدور الحالي</span><strong>${uEsc(roleLabels[row.role]||row.role)}</strong></div><div class="user-field"><span>تاريخ الإنشاء</span><strong>${uEsc(uDate(row.created_at))}</strong></div><div class="user-field"><span>آخر تحديث</span><strong>${uEsc(uDate(row.updated_at))}</strong></div></div>${self?`<div class="self-note">هذا حسابك الحالي؛ لا يمكن تعطيله أو خفض صلاحيته من هذه الشاشة.</div>`:''}<div class="user-actions"><label>الدور<select data-user-role ${self?'disabled':''}>${Object.entries(roleLabels).map(([v,l])=>`<option value="${v}" ${row.role===v?'selected':''}>${l}</option>`).join('')}</select></label><label>كلمة مرور جديدة<input data-user-password type="password" minlength="10" maxlength="128" placeholder="اتركها فارغة دون تغيير"></label><label class="toggle-row"><input data-user-active type="checkbox" ${row.is_active?'checked':''} ${self?'disabled':''}> حساب نشط</label><button class="primary compact" data-user-save>حفظ</button><span class="inline-message" role="status"></span></div></article>`}).join('')}</div>`:'<div class="empty">لا توجد حسابات بهذه الحالة.</div>'}</section>`}
async function openUsers(){u$('#pageTitle').textContent='المستخدمون والصلاحيات';document.querySelectorAll('#adminNav [data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='users'));u$('#sidebar').classList.remove('open');u$('#backdrop').classList.remove('show');u$('#backdrop').hidden=true;u$('#content').innerHTML='<div class="loading">جاري تحميل المستخدمين...</div>';try{currentUser=await uApi('/api/auth/me');if(currentUser?.role!=='admin'){u$('#content').innerHTML='<div class="error">هذه الصفحة متاحة لمدير النظام فقط.</div>';return}const data=await uApi('/api/admin/users');usersRows=Array.isArray(data)?data:[];renderUsers()}catch(e){if(e.status===401){sessionStorage.removeItem(U_TOKEN);location.reload();return}u$('#content').innerHTML=`<div class="error">${uEsc(e.message)}</div>`}}
async function createUser(form){const msg=form.querySelector('.inline-message'),button=form.querySelector('button[type="submit"]');const body={name:form.elements.name.value.trim(),email:form.elements.email.value.trim(),password:form.elements.password.value,role:form.elements.role.value};try{button.disabled=true;msg.textContent='جاري الإنشاء...';await uApi('/api/admin/users',{method:'POST',body});msg.textContent='تم إنشاء الحساب';await openUsers()}catch(e){msg.textContent=e.message;button.disabled=false}}
async function saveUser(button){const card=button.closest('.user-card'),msg=card.querySelector('.inline-message'),password=card.querySelector('[data-user-password]').value;const body={role:card.querySelector('[data-user-role]').value,is_active:card.querySelector('[data-user-active]').checked};if(password)body.password=password;try{button.disabled=true;msg.textContent='جاري الحفظ...';await uApi(`/api/admin/users/${card.dataset.userId}`,{method:'PATCH',body});msg.textContent='تم الحفظ';await openUsers()}catch(e){msg.textContent=e.message;button.disabled=false}}
document.addEventListener('click',async e=>{const nav=e.target.closest('#adminNav [data-view="users"]');if(nav){e.preventDefault();e.stopImmediatePropagation();await openUsers();return}const filter=e.target.closest('[data-user-filter]');if(filter){userFilter=filter.dataset.userFilter;renderUsers();return}if(e.target.closest('[data-user-new]')){const slot=u$('[data-user-form-slot]');slot.innerHTML=renderCreateForm();slot.querySelector('input[name="name"]')?.focus();return}const save=e.target.closest('[data-user-save]');if(save)await saveUser(save)},true);
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-user-form]');if(!form)return;e.preventDefault();if(form.reportValidity())await createUser(form)},true);
(async()=>{try{const me=await uApi('/api/auth/me');const nav=document.querySelector('#adminNav [data-view="users"]');if(nav&&me?.role!=='admin')nav.hidden=true}catch{}})();
