const V_ORIGINS=['https://api.bunyan-sudan.org','https://bunyan-api-qhkf.onrender.com'];
const V_TOKEN='bunyan_v2_token',V_ORIGIN='bunyan_v2_origin';
const v$=s=>document.querySelector(s),vEsc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let volunteerRows=[],volunteerFilter='all',volunteerSearch='';
const volunteerStatuses=['جديد','نشط','متوقف','مكتمل'];
async function vApi(path,options={}){const token=sessionStorage.getItem(V_TOKEN)||'',preferred=sessionStorage.getItem(V_ORIGIN)||V_ORIGINS[0],headers={...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;if(options.body){headers['Content-Type']='application/json';options={...options,body:typeof options.body==='string'?options.body:JSON.stringify(options.body)}}let last;for(const origin of [preferred,...V_ORIGINS.filter(x=>x!==preferred)]){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);try{const r=await fetch(origin+path,{...options,headers,cache:'no-store',signal:controller.signal}),text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok){const e=new Error(data.error||`فشل الطلب (${r.status})`);e.status=r.status;throw e}sessionStorage.setItem(V_ORIGIN,origin);return data}catch(e){last=e;if(e.status&&e.status<500)break}finally{clearTimeout(timer)}}throw last||new Error('تعذر الاتصال بالخادم')}
function vFiltered(){const q=volunteerSearch.trim().toLowerCase();return volunteerRows.filter(r=>(volunteerFilter==='all'||String(r.status||'جديد')===volunteerFilter)&&(!q||[r.name,r.phone,r.email,r.skill].some(v=>String(v||'').toLowerCase().includes(q))))}
function vRender(){const list=vFiltered();v$('#content').innerHTML=`<section class="volunteer-workspace"><div class="section-head"><div><h3>المتطوعون</h3><p>إدارة بيانات المتطوعين والمهارات وساعات العمل.</p></div><button class="primary" data-volunteer-new>+ متطوع جديد</button></div><div class="volunteer-tools"><input data-volunteer-search value="${vEsc(volunteerSearch)}" placeholder="بحث بالاسم أو الهاتف أو المهارة"><select data-volunteer-filter><option value="all">كل الحالات (${volunteerRows.length})</option>${volunteerStatuses.map(s=>`<option value="${vEsc(s)}" ${volunteerFilter===s?'selected':''}>${vEsc(s)} (${volunteerRows.filter(x=>(x.status||'جديد')===s).length})</option>`).join('')}</select></div>${list.length?`<div class="volunteer-list">${list.map(r=>`<article class="volunteer-card" data-volunteer-id="${vEsc(r.id)}"><header><div><h4>${vEsc(r.name||'بدون اسم')}</h4><span>${vEsc(r.skill||'مهارة غير محددة')}</span></div><strong>${vEsc(r.status||'جديد')}</strong></header><div class="volunteer-grid"><div><span>الهاتف</span><b>${vEsc(r.phone||'—')}</b></div><div><span>البريد</span><b>${vEsc(r.email||'—')}</b></div><div><span>ساعات التطوع</span><b>${vEsc(r.hours??0)}</b></div></div><footer>${r.phone?`<a class="ghost compact" href="tel:${vEsc(String(r.phone).replace(/[^+\d]/g,''))}">اتصال</a>`:''}<button class="ghost compact" data-volunteer-edit>تعديل</button></footer></article>`).join('')}</div>`:'<div class="empty">لا توجد سجلات مطابقة.</div>'}<div id="volunteerModal" class="volunteer-modal" hidden></div></section>`}
function vForm(row={}){const modal=v$('#volunteerModal');modal.hidden=false;modal.innerHTML=`<form class="volunteer-form" data-volunteer-form data-id="${vEsc(row.id||'')}"><header><h3>${row.id?'تعديل متطوع':'إضافة متطوع'}</h3><button type="button" class="ghost compact" data-volunteer-close>×</button></header><label>الاسم الكامل<input name="name" value="${vEsc(row.name||'')}" required minlength="2"></label><label>رقم الهاتف<input name="phone" value="${vEsc(row.phone||'')}" required minlength="5"></label><label>البريد الإلكتروني<input name="email" type="email" value="${vEsc(row.email||'')}"></label><label>المهارة<input name="skill" value="${vEsc(row.skill||'')}"></label><label>ساعات التطوع<input name="hours" type="number" min="0" step="0.5" value="${vEsc(row.hours??0)}"></label><label>الحالة<select name="status">${volunteerStatuses.map(s=>`<option ${String(row.status||'جديد')===s?'selected':''}>${vEsc(s)}</option>`).join('')}</select></label><footer><button type="button" class="ghost" data-volunteer-close>إلغاء</button><button class="primary" type="submit">حفظ</button><span class="inline-message" role="status"></span></footer></form>`}
async function openVolunteers(){v$('#pageTitle').textContent='المتطوعون';document.querySelectorAll('#adminNav [data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view==='volunteers'));v$('#sidebar').classList.remove('open');v$('#backdrop').classList.remove('show');v$('#backdrop').hidden=true;v$('#content').innerHTML='<div class="loading">جاري تحميل المتطوعين...</div>';try{const rows=await vApi('/api/volunteers');volunteerRows=Array.isArray(rows)?rows:[];vRender()}catch(e){if(e.status===401){sessionStorage.removeItem(V_TOKEN);location.reload();return}v$('#content').innerHTML=`<div class="error">${vEsc(e.message)}</div><button class="ghost" data-volunteer-retry>إعادة المحاولة</button>`}}
document.addEventListener('click',async e=>{const nav=e.target.closest('#adminNav [data-view="volunteers"]');if(nav){e.preventDefault();e.stopImmediatePropagation();await openVolunteers();return}if(e.target.closest('[data-volunteer-new]')){vForm();return}if(e.target.closest('[data-volunteer-close]')){v$('#volunteerModal').hidden=true;return}if(e.target.closest('[data-volunteer-retry]')){await openVolunteers();return}const edit=e.target.closest('[data-volunteer-edit]');if(edit){const id=edit.closest('[data-volunteer-id]').dataset.volunteerId;vForm(volunteerRows.find(x=>String(x.id)===String(id))||{});return}},true);
document.addEventListener('input',e=>{if(e.target.matches('[data-volunteer-search]')){volunteerSearch=e.target.value;vRender()}},true);
document.addEventListener('change',e=>{if(e.target.matches('[data-volunteer-filter]')){volunteerFilter=e.target.value;vRender()}},true);
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-volunteer-form]');if(!form)return;e.preventDefault();e.stopImmediatePropagation();const msg=form.querySelector('.inline-message'),button=form.querySelector('button[type="submit"]'),fd=new FormData(form),body=Object.fromEntries(fd);body.hours=Number(body.hours||0);if(!body.email)body.email=null;try{button.disabled=true;msg.textContent='جاري الحفظ...';const id=form.dataset.id;await vApi(id?`/api/volunteers/${id}`:'/api/volunteers',{method:id?'PATCH':'POST',body});v$('#volunteerModal').hidden=true;await openVolunteers()}catch(err){msg.textContent=err.message;button.disabled=false}},true);
