import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import pg from 'pg';
import crypto from 'node:crypto';
import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';
import { rateLimit } from 'express-rate-limit';
import { z } from 'zod';

const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT || 8080);
const pool = new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.NODE_ENV==='production'?{rejectUnauthorized:false}:false});
const jwtSecret=process.env.JWT_SECRET;
if(!jwtSecret) throw new Error('JWT_SECRET is required');

const origins=new Set(['https://bunyan-sudan.org','https://www.bunyan-sudan.org','https://shumsphone96-sys.github.io',...String(process.env.CORS_ORIGIN||'').split(',').map(x=>x.trim()).filter(Boolean)]);
app.set('trust proxy',1);
app.disable('x-powered-by');
app.use((req,res,next)=>{req.requestId=req.get('x-request-id')||crypto.randomUUID();res.setHeader('X-Request-ID',req.requestId);next()});
app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'},contentSecurityPolicy:false}));
app.use(cors({origin:(o,cb)=>!o||origins.has(o)?cb(null,true):cb(new Error('Not allowed by CORS')),methods:['GET','POST','PATCH','DELETE','OPTIONS'],allowedHeaders:['Content-Type','Authorization','X-Request-ID']}));
app.options('*',cors());
app.use(express.json({limit:'2mb'}));
app.use(express.urlencoded({limit:'2mb',extended:true}));
app.use('/api/',rateLimit({windowMs:15*60*1000,limit:400,standardHeaders:'draft-7',legacyHeaders:false,message:{error:'طلبات كثيرة. حاول لاحقاً.'}}));
const authLimit=rateLimit({windowMs:15*60*1000,limit:12,standardHeaders:'draft-7',legacyHeaders:false,message:{error:'محاولات كثيرة. حاول بعد 15 دقيقة.'}});
const publicWriteLimit=rateLimit({windowMs:60*60*1000,limit:30,standardHeaders:'draft-7',legacyHeaders:false,message:{error:'تم تجاوز الحد المسموح مؤقتاً.'}});

const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const sign=u=>jwt.sign({sub:u.id,role:u.role,name:u.name},jwtSecret,{expiresIn:'8h',issuer:'bunyan-api',audience:'bunyan-admin'});
function auth(req,res,next){const t=req.headers.authorization?.replace(/^Bearer\s+/i,'');if(!t)return res.status(401).json({error:'يلزم تسجيل الدخول'});try{req.user=jwt.verify(t,jwtSecret,{issuer:'bunyan-api',audience:'bunyan-admin'});next()}catch{return res.status(401).json({error:'جلسة غير صالحة أو منتهية'})}}
const allow=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'ليست لديك الصلاحية المطلوبة'});
async function audit(req,action,type,id=null,metadata={}){try{await pool.query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata,ip_address) VALUES($1,$2,$3,$4,$5,$6)',[req.user?.sub||null,action,type,id,metadata,req.ip])}catch(e){console.error('audit',e.message)}}
const slugify=v=>String(v||'').trim().toLowerCase().replace(/[\s_]+/g,'-').replace(/[^\p{L}\p{N}-]+/gu,'').replace(/-+/g,'-').replace(/^-|-$/g,'')||crypto.randomUUID().slice(0,8);

const allowedMime=new Set(['application/pdf','image/jpeg','image/png','image/webp']);
const makeUpload=(field,max)=>multer({storage:multer.memoryStorage(),limits:{fileSize:max,files:1},fileFilter:(_r,f,cb)=>allowedMime.has(f.mimetype)?cb(null,true):cb(new Error('الملف يجب أن يكون PDF أو صورة JPG/PNG/WEBP'))}).single(field);
const uploadProject=makeUpload('file',5*1024*1024),uploadReceipt=makeUpload('receipt',3*1024*1024);
const mw=u=>(req,res,next)=>u(req,res,e=>e?res.status(400).json({error:e.code==='LIMIT_FILE_SIZE'?'حجم الملف أكبر من المسموح':e.message}):next());

app.get('/health',asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({ok:true,service:'bunyan-cloud-api',version:'8.0.0',time:new Date().toISOString()})}));
app.post('/api/setup',authLimit,asyncRoute(async(req,res)=>{const c=await pool.query('SELECT count(*)::int count FROM users');if(c.rows[0].count)return res.status(409).json({error:'تم إعداد النظام مسبقاً'});const d=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10).max(128)}).parse(req.body);const {rows}=await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[d.name,d.email.toLowerCase(),await bcrypt.hash(d.password,12),'admin']);res.status(201).json({user:rows[0],token:sign(rows[0])})}));
app.post('/api/auth/login',authLimit,asyncRoute(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string().min(1).max(128)}).parse(req.body);const {rows}=await pool.query('SELECT id,name,email,password_hash,role,is_active FROM users WHERE email=$1',[d.email.toLowerCase()]);const u=rows[0];if(!u||!u.is_active||!(await bcrypt.compare(d.password,u.password_hash)))return res.status(401).json({error:'بيانات الدخول غير صحيحة'});const safe={id:u.id,name:u.name,email:u.email,role:u.role};await audit({...req,user:{sub:u.id}},'login','auth',u.id);res.json({user:safe,token:sign(safe)})}));
app.get('/api/auth/me',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,name,email,role,created_at,updated_at FROM users WHERE id=$1 AND is_active=true',[req.user.sub]);res.json(rows[0]||null)}));

app.get(['/api/public/projects','/api/projects'],asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT p.id,p.slug,p.name,p.summary,p.status,p.progress,p.beneficiaries_target,p.budget,p.currency,p.cover_image_url,p.created_at,coalesce(sum(d.amount) FILTER (WHERE d.status='verified' AND d.currency=p.currency),0) raised FROM projects p LEFT JOIN donations d ON d.project_id=p.id WHERE p.is_public=true GROUP BY p.id ORDER BY p.created_at DESC`);res.json(rows)}));
app.get('/api/public/projects/:slug',asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT p.*,coalesce((SELECT sum(amount) FROM donations d WHERE d.project_id=p.id AND d.status='verified' AND d.currency=p.currency),0) raised FROM projects p WHERE p.slug=$1 AND p.is_public=true`,[req.params.slug]);if(!rows[0])return res.status(404).json({error:'المشروع غير موجود'});const id=rows[0].id;const [updates,expenses,files]=await Promise.all([pool.query('SELECT id,title,body,published_at,created_at FROM project_updates WHERE project_id=$1 AND is_public=true ORDER BY created_at DESC',[id]),pool.query('SELECT id,title,amount,currency,spent_at,category,notes FROM project_expenses WHERE project_id=$1 AND is_public=true ORDER BY spent_at DESC',[id]),pool.query('SELECT id,file_name,mime_type,size_bytes,kind,created_at FROM project_files WHERE project_id=$1 AND is_public=true ORDER BY created_at DESC',[id])]);res.json({...rows[0],updates:updates.rows,expenses:expenses.rows,files:files.rows})}));
app.get('/api/public/project-files/:id',asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT file_name,mime_type,file_data FROM project_files WHERE id=$1 AND is_public=true',[req.params.id]);if(!rows[0])return res.status(404).end();res.type(rows[0].mime_type).set('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(rows[0].file_name)}`).send(rows[0].file_data)}));
app.get(['/api/public/news','/api/news'],asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT id,title,body,published_at,created_at FROM news WHERE is_public=true AND published_at IS NOT NULL ORDER BY created_at DESC');res.json(rows)}));
app.post(['/api/public/participation-requests','/api/join'],publicWriteLimit,asyncRoute(async(req,res)=>{const d=z.object({name:z.string().min(2).max(120),phone:z.string().min(5).max(40),role:z.string().min(2).max(100),message:z.string().max(1000).optional()}).parse(req.body);const {rows}=await pool.query('INSERT INTO participation_requests(name,phone,role,message) VALUES($1,$2,$3,$4) RETURNING id,created_at',[d.name,d.phone,d.role,d.message||null]);res.status(201).json(rows[0])}));

app.post(['/api/public/donations','/api/donations'],publicWriteLimit,mw(uploadReceipt),asyncRoute(async(req,res)=>{const d=z.object({donor:z.string().min(2).max(120),phone:z.string().max(40).optional().or(z.literal('')),amount:z.coerce.number().positive(),currency:z.enum(['SDG','SAR','USD']),projectId:z.string().uuid().optional().or(z.literal('')),projectName:z.string().max(160).optional().or(z.literal('')),method:z.string().max(100).optional().or(z.literal('')),reference:z.string().max(160).optional().or(z.literal(''))}).parse(req.body);const client=await pool.connect();try{await client.query('BEGIN');const seq=(await client.query("SELECT nextval('donation_receipt_seq') n")).rows[0].n;const receipt=`BN-${new Date().getFullYear()}-${String(seq).padStart(7,'0')}`;const verifyToken=crypto.randomBytes(24).toString('hex');const {rows}=await client.query('INSERT INTO donations(donor,phone,amount,currency,project_id,project_name,method,reference,receipt_number,verification_token) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,status,receipt_number,verification_token,created_at',[d.donor,d.phone||null,d.amount,d.currency,d.projectId||null,d.projectName||null,d.method||null,d.reference||null,receipt,verifyToken]);if(req.file)await client.query('INSERT INTO donation_attachments(donation_id,file_name,mime_type,size_bytes,file_data) VALUES($1,$2,$3,$4,$5)',[rows[0].id,req.file.originalname,req.file.mimetype,req.file.size,req.file.buffer]);await client.query('COMMIT');res.status(201).json(rows[0])}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));

app.get('/api/public/receipts/verify/:token',asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT d.receipt_number,d.donor,d.amount,d.currency,d.project_name,d.method,d.reference,d.status,d.created_at,d.verified_at,p.name project FROM donations d LEFT JOIN projects p ON p.id=d.project_id WHERE d.verification_token=$1`,[req.params.token]);if(!rows[0])return res.status(404).json({valid:false,error:'السند غير موجود'});res.json({valid:true,...rows[0]})}));
app.get('/api/public/receipts/:token.pdf',asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT d.receipt_number,d.donor,d.amount,d.currency,coalesce(p.name,d.project_name,'General Donation') project,d.method,d.reference,d.status,d.created_at,d.verification_token FROM donations d LEFT JOIN projects p ON p.id=d.project_id WHERE d.verification_token=$1`,[req.params.token]);const d=rows[0];if(!d)return res.status(404).json({error:'السند غير موجود'});const verifyUrl=`${process.env.PUBLIC_API_URL||'https://api.bunyan-sudan.org'}/api/public/receipts/verify/${d.verification_token}`;const qr=await QRCode.toDataURL(verifyUrl,{margin:1,width:220});res.setHeader('Content-Type','application/pdf');res.setHeader('Content-Disposition',`inline; filename="${d.receipt_number}.pdf"`);const doc=new PDFDocument({size:'A4',margin:50,info:{Title:`BUNYAN Receipt ${d.receipt_number}`,Author:'BUNYAN'}});doc.pipe(res);doc.fontSize(24).text('BUNYAN', {align:'center'}).moveDown(.2);doc.fontSize(13).text('Official Donation Receipt',{align:'center'}).moveDown(1.5);doc.roundedRect(50,120,495,260,12).stroke();doc.fontSize(11);const rowsText=[['Receipt No.',d.receipt_number],['Donor',d.donor],['Amount',`${Number(d.amount).toLocaleString('en-GB')} ${d.currency}`],['Project',d.project],['Method',d.method||'-'],['Reference',d.reference||'-'],['Status',d.status],['Date',new Date(d.created_at).toLocaleString('en-GB')]];let y=145;for(const [k,v] of rowsText){doc.font('Helvetica-Bold').text(k,75,y,{width:120});doc.font('Helvetica').text(String(v),200,y,{width:300});y+=28}doc.image(qr,205,405,{width:180});doc.fontSize(9).text('Scan the QR code to verify this receipt online.',50,595,{align:'center',width:495});doc.fontSize(8).fillColor('#666').text(verifyUrl,50,625,{align:'center',width:495});doc.end()}));

const resources={projects:{table:'projects',fields:['slug','name','summary','description','status','progress','beneficiaries_target','budget','currency','cover_image_url','location','start_date','end_date','is_public']},beneficiaries:{table:'beneficiaries',fields:['name','phone','service','status','project_id','notes']},volunteers:{table:'volunteers',fields:['name','phone','email','skill','hours','status']},news:{table:'news',fields:['title','body','published_at','is_public']},requests:{table:'participation_requests',fields:['name','phone','role','message','status']},donations:{table:'donations',fields:['donor','phone','amount','currency','project_id','project_name','method','reference','status']},expenses:{table:'project_expenses',fields:['project_id','title','amount','currency','spent_at','category','notes','is_public']},updates:{table:'project_updates',fields:['project_id','title','body','published_at','is_public']}};
app.get('/api/dashboard',auth,asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT (SELECT count(*) FROM projects)::int projects,(SELECT count(*) FROM beneficiaries)::int beneficiaries,(SELECT count(*) FROM volunteers)::int volunteers,(SELECT count(*) FROM participation_requests WHERE status='new')::int new_requests,(SELECT count(*) FROM donations)::int donations,(SELECT count(*) FROM project_expenses)::int expenses`);res.json(rows[0])}));
app.get('/api/audit-logs',auth,allow('admin','manager'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 1000');res.json(rows)}));
app.get('/api/backup/export',auth,allow('admin'),asyncRoute(async(req,res)=>{const tables=['projects','project_updates','project_expenses','beneficiaries','volunteers','donations','news','participation_requests','audit_logs'];const backup={version:'8.0.0',createdAt:new Date().toISOString(),data:{}};for(const t of tables)backup.data[t]=(await pool.query(`SELECT * FROM ${t} ORDER BY created_at DESC`)).rows;await audit(req,'export','backup');res.setHeader('Content-Disposition',`attachment; filename="bunyan-backup-${new Date().toISOString().slice(0,10)}.json"`);res.json(backup)}));
app.get('/api/:resource',auth,asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});res.json((await pool.query(`SELECT * FROM ${c.table} ORDER BY created_at DESC LIMIT 1000`)).rows)}));
app.post('/api/:resource',auth,allow('admin','manager','staff'),asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});if(req.params.resource==='projects'&&!req.body.slug)req.body.slug=slugify(req.body.name);const e=c.fields.filter(k=>Object.hasOwn(req.body,k)).map(k=>[k,req.body[k]]);if(!e.length)return res.status(400).json({error:'لا توجد بيانات صالحة'});const {rows}=await pool.query(`INSERT INTO ${c.table}(${e.map(x=>x[0]).join(',')}) VALUES(${e.map((_,i)=>`$${i+1}`).join(',')}) RETURNING *`,e.map(x=>x[1]));await audit(req,'create',req.params.resource,rows[0].id);res.status(201).json(rows[0])}));
app.patch('/api/:resource/:id',auth,allow('admin','manager','staff'),asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});const e=c.fields.filter(k=>Object.hasOwn(req.body,k)).map(k=>[k,req.body[k]]);if(!e.length)return res.status(400).json({error:'لا توجد تغييرات صالحة'});const vals=e.map(x=>x[1]);const {rows}=await pool.query(`UPDATE ${c.table} SET ${e.map(([k],i)=>`${k}=$${i+1}`).join(',')},updated_at=now() WHERE id=$${vals.length+1} RETURNING *`,[...vals,req.params.id]);if(!rows[0])return res.status(404).json({error:'السجل غير موجود'});if(req.params.resource==='donations'&&req.body.status==='verified')await pool.query('UPDATE donations SET verified_at=now(),verified_by=$1 WHERE id=$2',[req.user.sub,req.params.id]);await audit(req,'update',req.params.resource,req.params.id,req.body);res.json(rows[0])}));
app.delete('/api/:resource/:id',auth,allow('admin','manager'),asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});const r=await pool.query(`DELETE FROM ${c.table} WHERE id=$1`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'السجل غير موجود'});await audit(req,'delete',req.params.resource,req.params.id);res.status(204).end()}));

app.post('/api/projects/:id/files',auth,allow('admin','manager','staff'),mw(uploadProject),asyncRoute(async(req,res)=>{if(!req.file)return res.status(400).json({error:'اختر ملفاً'});const kind=String(req.body.kind||'document').slice(0,30),isPublic=String(req.body.is_public||'false')==='true';const {rows}=await pool.query('INSERT INTO project_files(project_id,file_name,mime_type,size_bytes,file_data,kind,is_public,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,file_name,mime_type,size_bytes,kind,is_public,created_at',[req.params.id,req.file.originalname,req.file.mimetype,req.file.size,req.file.buffer,kind,isPublic,req.user.sub]);await audit(req,'upload','project_file',rows[0].id,{projectId:req.params.id});res.status(201).json(rows[0])}));
app.get('/api/projects/:id/files',auth,asyncRoute(async(req,res)=>res.json((await pool.query('SELECT id,file_name,mime_type,size_bytes,kind,is_public,created_at FROM project_files WHERE project_id=$1 ORDER BY created_at DESC',[req.params.id])).rows)));
app.get('/api/project-files/:id/download',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT file_name,mime_type,file_data FROM project_files WHERE id=$1',[req.params.id]);if(!rows[0])return res.status(404).end();res.type(rows[0].mime_type).set('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(rows[0].file_name)}`).send(rows[0].file_data)}));
app.delete('/api/project-files/:id',auth,allow('admin','manager'),asyncRoute(async(req,res)=>{await pool.query('DELETE FROM project_files WHERE id=$1',[req.params.id]);await audit(req,'delete','project_file',req.params.id);res.status(204).end()}));
app.get('/api/donations/:id/receipt',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,file_name,mime_type,size_bytes,created_at FROM donation_attachments WHERE donation_id=$1 ORDER BY created_at DESC LIMIT 1',[req.params.id]);res.json(rows[0]||null)}));
app.get('/api/donation-receipts/:id/download',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT file_name,mime_type,file_data FROM donation_attachments WHERE id=$1',[req.params.id]);if(!rows[0])return res.status(404).end();res.type(rows[0].mime_type).set('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(rows[0].file_name)}`).send(rows[0].file_data)}));

app.use((err,req,res,_next)=>{console.error(`[${req.requestId}]`,err);if(res.headersSent)return;if(err instanceof z.ZodError)return res.status(400).json({error:'بيانات غير صالحة',details:err.flatten(),requestId:req.requestId});if(err?.message==='Not allowed by CORS')return res.status(403).json({error:'المصدر غير مسموح',requestId:req.requestId});if(err?.code==='23505')return res.status(409).json({error:'القيمة مستخدمة مسبقاً',requestId:req.requestId});res.status(500).json({error:process.env.NODE_ENV==='production'?'حدث خطأ داخلي':err.message,requestId:req.requestId})});
app.listen(port,()=>console.log(`BUNYAN Cloud API 8.0.0 listening on ${port}`));
