import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import multer from 'multer';
import pg from 'pg';
import crypto from 'node:crypto';
import { z } from 'zod';

const { Pool } = pg;
const app = express();
const port = Number(process.env.PORT || 8080);
const pool = new Pool({ connectionString: process.env.DATABASE_URL, ssl: process.env.NODE_ENV === 'production' ? { rejectUnauthorized:false } : false });
const jwtSecret = process.env.JWT_SECRET;
if (!jwtSecret) throw new Error('JWT_SECRET is required');

const allowedOrigins = new Set(['https://bunyan-sudan.org','https://www.bunyan-sudan.org','https://shumsphone96-sys.github.io',...String(process.env.CORS_ORIGIN||'').split(',').map(v=>v.trim()).filter(Boolean)]);
app.set('trust proxy',1);
app.use((req,res,next)=>{ req.requestId=req.get('x-request-id')||crypto.randomUUID(); res.setHeader('X-Request-ID',req.requestId); next(); });
app.use(helmet({ crossOriginResourcePolicy:{ policy:'cross-origin' } }));
app.use(cors({ origin:(origin,cb)=>!origin||allowedOrigins.has(origin)?cb(null,true):cb(new Error('Not allowed by CORS')), methods:['GET','POST','PATCH','DELETE','OPTIONS'], allowedHeaders:['Content-Type','Authorization','X-Request-ID'] }));
app.options('*',cors());
app.use(express.json({limit:'12mb'}));
app.use(express.urlencoded({limit:'12mb',extended:true}));

const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const sign=user=>jwt.sign({sub:user.id,role:user.role,name:user.name},jwtSecret,{expiresIn:'8h'});
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const slugify=v=>String(v||'').trim().toLowerCase().replace(/[\s_]+/g,'-').replace(/[^\p{L}\p{N}-]+/gu,'').replace(/-+/g,'-').replace(/^-|-$/g,'')||crypto.randomUUID().slice(0,8);
function auth(req,res,next){ const token=req.headers.authorization?.replace(/^Bearer\s+/i,''); if(!token)return res.status(401).json({error:'يلزم تسجيل الدخول'}); try{req.user=jwt.verify(token,jwtSecret);next();}catch{return res.status(401).json({error:'جلسة غير صالحة أو منتهية'});} }
const allow=(...roles)=>(req,res,next)=>roles.includes(req.user.role)?next():res.status(403).json({error:'ليست لديك الصلاحية المطلوبة'});
async function audit(req,action,entityType,entityId=null,metadata={}){try{await pool.query('INSERT INTO audit_logs(user_id,action,entity_type,entity_id,metadata,ip_address) VALUES($1,$2,$3,$4,$5,$6)',[req.user?.sub||null,action,entityType,entityId,metadata,req.ip]);}catch(e){console.error('audit',e.message)}}

const loginAttempts=new Map();
function loginGuard(req,res,next){ const key=req.ip; const now=Date.now(); const row=loginAttempts.get(key)||{count:0,until:0}; if(row.until>now)return res.status(429).json({error:'محاولات كثيرة. حاول بعد عدة دقائق.'}); req.loginAttempt=row; next(); }
function loginFailed(req){ const row=req.loginAttempt||{count:0,until:0}; row.count++; if(row.count>=5){row.until=Date.now()+15*60*1000;row.count=0;} loginAttempts.set(req.ip,row); }
function loginPassed(req){loginAttempts.delete(req.ip)}

const adminPanelUrl=process.env.ADMIN_PANEL_URL||'https://bunyan-sudan.org';
const notificationEmail=process.env.NOTIFICATION_EMAIL||process.env.ADMIN_EMAIL||'';
async function sendEmailAlert({subject,title,fields,to=notificationEmail}){if(!process.env.RESEND_API_KEY||!to)return;const rows=Object.entries(fields).map(([k,v])=>`<tr><td style="padding:8px;border:1px solid #ddd;font-weight:700">${esc(k)}</td><td style="padding:8px;border:1px solid #ddd">${esc(v)}</td></tr>`).join('');const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${process.env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({from:process.env.EMAIL_FROM||'BUNYAN <onboarding@resend.dev>',to:[to],subject,html:`<div dir="rtl"><h2>${esc(title)}</h2><table>${rows}</table><p><a href="${esc(adminPanelUrl)}">فتح لوحة الإدارة</a></p></div>`})});if(!r.ok)throw new Error(`Resend ${r.status}`)}
async function sendTelegramAlert({title,fields}){const token=process.env.TELEGRAM_BOT_TOKEN,chatId=process.env.TELEGRAM_CHAT_ID;if(!token||!chatId)return;const text=`📥 <b>${esc(title)}</b>\n\n${Object.entries(fields).map(([k,v])=>`<b>${esc(k)}:</b> ${esc(v)}`).join('\n')}`;const r=await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text,parse_mode:'HTML',disable_web_page_preview:true})});if(!r.ok)throw new Error(`Telegram ${r.status}`)}
function dispatchAlerts(payload){Promise.allSettled([sendEmailAlert(payload),sendTelegramAlert(payload)]).then(rs=>rs.forEach(r=>r.status==='rejected'&&console.error(r.reason)))}

const allowedMimeTypes=new Set(['application/pdf','image/jpeg','image/png','image/webp']);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:5*1024*1024,files:1},fileFilter:(_r,f,cb)=>allowedMimeTypes.has(f.mimetype)?cb(null,true):cb(new Error('الملف يجب أن يكون PDF أو صورة JPG/PNG/WEBP'))}).single('file');
const uploadMw=(req,res,next)=>upload(req,res,e=>e?res.status(400).json({error:e.code==='LIMIT_FILE_SIZE'?'حجم الملف يجب ألا يتجاوز 5 ميغابايت':e.message}):next());
const receiptUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:3*1024*1024,files:1},fileFilter:(_r,f,cb)=>allowedMimeTypes.has(f.mimetype)?cb(null,true):cb(new Error('إشعار غير مدعوم'))}).single('receipt');
const receiptMw=(req,res,next)=>receiptUpload(req,res,e=>e?res.status(400).json({error:e.code==='LIMIT_FILE_SIZE'?'حجم الإشعار يجب ألا يتجاوز 3 ميغابايت':e.message}):next());

app.get('/health',asyncRoute(async(_req,res)=>{await pool.query('SELECT 1');res.json({ok:true,service:'bunyan-cloud-api',version:'7.0.0',time:new Date().toISOString()})}));
app.post('/api/setup',asyncRoute(async(req,res)=>{const c=await pool.query('SELECT count(*)::int count FROM users');if(c.rows[0].count)return res.status(409).json({error:'تم إعداد النظام مسبقاً'});const d=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10)}).parse(req.body);const hash=await bcrypt.hash(d.password,12);const {rows}=await pool.query('INSERT INTO users(name,email,password_hash,role) VALUES($1,$2,$3,$4) RETURNING id,name,email,role',[d.name,d.email.toLowerCase(),hash,'admin']);res.status(201).json({user:rows[0],token:sign(rows[0])})}));
app.post('/api/auth/login',loginGuard,asyncRoute(async(req,res)=>{const d=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body);const {rows}=await pool.query('SELECT id,name,email,password_hash,role,is_active FROM users WHERE email=$1',[d.email.toLowerCase()]);const u=rows[0];if(!u||!u.is_active||!(await bcrypt.compare(d.password,u.password_hash))){loginFailed(req);return res.status(401).json({error:'بيانات الدخول غير صحيحة'})}loginPassed(req);const safe={id:u.id,name:u.name,email:u.email,role:u.role};res.json({user:safe,token:sign(safe)})}));
app.get('/api/auth/me',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,name,email,role,created_at,updated_at FROM users WHERE id=$1 AND is_active=true',[req.user.sub]);res.json(rows[0]||null)}));
app.post('/api/auth/forgot-password',asyncRoute(async(req,res)=>{const {email}=z.object({email:z.string().email()}).parse(req.body);const generic={ok:true,message:'إذا كان البريد مسجلاً فسيصل رمز التحقق خلال دقائق.'};const {rows}=await pool.query('SELECT id,name,email,is_active FROM users WHERE email=$1',[email.toLowerCase()]);const u=rows[0];if(!u||!u.is_active)return res.json(generic);const code=String(crypto.randomInt(100000,1000000));const hash=await bcrypt.hash(code,10);await pool.query('UPDATE password_reset_codes SET used_at=now() WHERE user_id=$1 AND used_at IS NULL',[u.id]);await pool.query("INSERT INTO password_reset_codes(user_id,code_hash,expires_at) VALUES($1,$2,now()+interval '15 minutes')",[u.id,hash]);await sendEmailAlert({to:u.email,subject:'رمز إعادة تعيين كلمة سر بُنْيَان',title:'إعادة تعيين كلمة السر',fields:{'رمز التحقق':code,'الصلاحية':'15 دقيقة'}});res.json(generic)}));
app.post('/api/auth/reset-password',asyncRoute(async(req,res)=>{const d=z.object({email:z.string().email(),code:z.string().regex(/^\d{6}$/),newPassword:z.string().min(10).max(128)}).parse(req.body);const ur=await pool.query('SELECT id,is_active FROM users WHERE email=$1',[d.email.toLowerCase()]);const u=ur.rows[0];if(!u||!u.is_active)return res.status(400).json({error:'الرمز غير صحيح أو منتهي'});const rr=await pool.query("SELECT id,code_hash,attempts FROM password_reset_codes WHERE user_id=$1 AND used_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1",[u.id]);const r=rr.rows[0];if(!r||r.attempts>=5||!(await bcrypt.compare(d.code,r.code_hash))){if(r)await pool.query('UPDATE password_reset_codes SET attempts=attempts+1 WHERE id=$1',[r.id]);return res.status(400).json({error:'الرمز غير صحيح أو منتهي'})}await pool.query('UPDATE users SET password_hash=$1,updated_at=now() WHERE id=$2',[await bcrypt.hash(d.newPassword,12),u.id]);await pool.query('UPDATE password_reset_codes SET used_at=now() WHERE user_id=$1 AND used_at IS NULL',[u.id]);res.json({ok:true})}));

app.get(['/api/public/projects','/api/projects'],asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT p.id,p.slug,p.name,p.summary,p.status,p.progress,p.beneficiaries_target,p.budget,p.currency,p.cover_image_url,p.created_at,coalesce(sum(d.amount) FILTER (WHERE d.status='verified' AND d.currency=p.currency),0) raised FROM projects p LEFT JOIN donations d ON d.project_id=p.id WHERE p.is_public=true GROUP BY p.id ORDER BY p.created_at DESC`);res.json(rows)}));
app.get('/api/public/projects/:slug',asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT p.*,coalesce((SELECT sum(amount) FROM donations d WHERE d.project_id=p.id AND d.status='verified' AND d.currency=p.currency),0) raised FROM projects p WHERE p.slug=$1 AND p.is_public=true`,[req.params.slug]);if(!rows[0])return res.status(404).json({error:'المشروع غير موجود'});const [updates,expenses,files]=await Promise.all([pool.query('SELECT id,title,body,published_at,created_at FROM project_updates WHERE project_id=$1 AND is_public=true ORDER BY created_at DESC',[rows[0].id]),pool.query('SELECT id,title,amount,currency,spent_at,category,notes FROM project_expenses WHERE project_id=$1 AND is_public=true ORDER BY spent_at DESC',[rows[0].id]),pool.query("SELECT id,file_name,mime_type,size_bytes,kind,created_at FROM project_files WHERE project_id=$1 AND is_public=true ORDER BY created_at DESC",[rows[0].id])]);res.json({...rows[0],updates:updates.rows,expenses:expenses.rows,files:files.rows})}));
app.get('/api/public/project-files/:id',asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT file_name,mime_type,file_data FROM project_files WHERE id=$1 AND is_public=true',[req.params.id]);if(!rows[0])return res.status(404).end();res.setHeader('Content-Type',rows[0].mime_type);res.setHeader('Content-Disposition',`inline; filename*=UTF-8''${encodeURIComponent(rows[0].file_name)}`);res.send(rows[0].file_data)}));
app.get(['/api/public/news','/api/news'],asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT id,title,body,published_at,created_at FROM news WHERE is_public=true AND published_at IS NOT NULL ORDER BY created_at DESC');res.json(rows)}));
app.post(['/api/public/participation-requests','/api/join'],asyncRoute(async(req,res)=>{const d=z.object({name:z.string().min(2).max(120),phone:z.string().min(5).max(40),role:z.string().min(2).max(100),message:z.string().max(1000).optional()}).parse(req.body);const {rows}=await pool.query('INSERT INTO participation_requests(name,phone,role,message) VALUES($1,$2,$3,$4) RETURNING id,created_at',[d.name,d.phone,d.role,d.message||null]);dispatchAlerts({subject:`طلب مشاركة جديد من ${d.name}`,title:'طلب مشاركة جديد',fields:{الاسم:d.name,الهاتف:d.phone,النوع:d.role}});res.status(201).json(rows[0])}));
app.post(['/api/public/donations','/api/donations'],receiptMw,asyncRoute(async(req,res)=>{const d=z.object({donor:z.string().min(2).max(120),phone:z.string().max(40).optional().or(z.literal('')),amount:z.coerce.number().positive(),currency:z.enum(['SDG','SAR','USD']),projectId:z.string().uuid().optional().or(z.literal('')),projectName:z.string().max(160).optional().or(z.literal('')),method:z.string().max(100).optional().or(z.literal('')),reference:z.string().max(160).optional().or(z.literal(''))}).parse(req.body);const client=await pool.connect();try{await client.query('BEGIN');const receiptNo=`BN-${new Date().getFullYear()}-${Date.now().toString().slice(-8)}`;const {rows}=await client.query('INSERT INTO donations(donor,phone,amount,currency,project_id,project_name,method,reference,receipt_number) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,status,receipt_number,created_at',[d.donor,d.phone||null,d.amount,d.currency,d.projectId||null,d.projectName||null,d.method||null,d.reference||null,receiptNo]);if(req.file)await client.query('INSERT INTO donation_attachments(donation_id,file_name,mime_type,size_bytes,file_data) VALUES($1,$2,$3,$4,$5)',[rows[0].id,req.file.originalname,req.file.mimetype,req.file.size,req.file.buffer]);await client.query('COMMIT');dispatchAlerts({subject:`تبرع جديد: ${d.amount} ${d.currency}`,title:'وصل إشعار تبرع جديد',fields:{المتبرع:d.donor,المبلغ:`${d.amount} ${d.currency}`,المشروع:d.projectName||'عام'}});res.status(201).json({ok:true,...rows[0]})}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}));

const resources={projects:{table:'projects',fields:['slug','name','summary','description','status','progress','beneficiaries_target','budget','currency','cover_image_url','location','start_date','end_date','is_public']},beneficiaries:{table:'beneficiaries',fields:['name','phone','service','status','project_id','notes']},volunteers:{table:'volunteers',fields:['name','phone','email','skill','hours','status']},news:{table:'news',fields:['title','body','published_at','is_public']},requests:{table:'participation_requests',fields:['name','phone','role','message','status']},donations:{table:'donations',fields:['donor','phone','amount','currency','project_id','project_name','method','reference','status']},expenses:{table:'project_expenses',fields:['project_id','title','amount','currency','spent_at','category','notes','is_public']},updates:{table:'project_updates',fields:['project_id','title','body','published_at','is_public']}};
app.get('/api/dashboard',auth,asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT (SELECT count(*) FROM projects)::int projects,(SELECT count(*) FROM beneficiaries)::int beneficiaries,(SELECT count(*) FROM volunteers)::int volunteers,(SELECT count(*) FROM participation_requests WHERE status='new')::int new_requests,(SELECT count(*) FROM donations)::int donations,(SELECT count(*) FROM project_expenses)::int expenses`);res.json(rows[0])}));
app.get('/api/audit-logs',auth,allow('admin','manager'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT a.*,u.name user_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 1000');res.json(rows)}));
app.get('/api/backup/export',auth,allow('admin'),asyncRoute(async(req,res)=>{const tables=['projects','project_updates','project_expenses','beneficiaries','volunteers','donations','news','participation_requests','audit_logs'];const backup={version:'7.0.0',createdAt:new Date().toISOString(),data:{}};for(const table of tables)backup.data[table]=(await pool.query(`SELECT * FROM ${table} ORDER BY created_at DESC`)).rows;await audit(req,'export','backup');res.setHeader('Content-Disposition',`attachment; filename="bunyan-backup-${new Date().toISOString().slice(0,10)}.json"`);res.json(backup)}));
app.get('/api/:resource',auth,asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});const {rows}=await pool.query(`SELECT * FROM ${c.table} ORDER BY created_at DESC LIMIT 1000`);res.json(rows)}));
app.post('/api/:resource',auth,allow('admin','manager','staff'),asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});if(req.params.resource==='projects'&&!req.body.slug)req.body.slug=slugify(req.body.name);const entries=c.fields.filter(k=>Object.hasOwn(req.body,k)).map(k=>[k,req.body[k]]);if(!entries.length)return res.status(400).json({error:'لا توجد بيانات صالحة'});const cols=entries.map(x=>x[0]),vals=entries.map(x=>x[1]),ph=vals.map((_,i)=>`$${i+1}`);const {rows}=await pool.query(`INSERT INTO ${c.table}(${cols.join(',')}) VALUES(${ph.join(',')}) RETURNING *`,vals);await audit(req,'create',req.params.resource,rows[0].id);res.status(201).json(rows[0])}));
app.patch('/api/:resource/:id',auth,allow('admin','manager','staff'),asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});const entries=c.fields.filter(k=>Object.hasOwn(req.body,k)).map(k=>[k,req.body[k]]);if(!entries.length)return res.status(400).json({error:'لا توجد تغييرات صالحة'});const vals=entries.map(x=>x[1]),set=entries.map(([k],i)=>`${k}=$${i+1}`).join(',');const {rows}=await pool.query(`UPDATE ${c.table} SET ${set},updated_at=now() WHERE id=$${vals.length+1} RETURNING *`,[...vals,req.params.id]);if(!rows[0])return res.status(404).json({error:'السجل غير موجود'});if(req.params.resource==='donations'&&req.body.status==='verified')await pool.query('UPDATE donations SET verified_at=now(),verified_by=$1 WHERE id=$2',[req.user.sub,req.params.id]);await audit(req,'update',req.params.resource,req.params.id,req.body);res.json(rows[0])}));
app.delete('/api/:resource/:id',auth,allow('admin','manager'),asyncRoute(async(req,res)=>{const c=resources[req.params.resource];if(!c)return res.status(404).json({error:'المورد غير موجود'});const r=await pool.query(`DELETE FROM ${c.table} WHERE id=$1`,[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'السجل غير موجود'});await audit(req,'delete',req.params.resource,req.params.id);res.status(204).end()}));

app.post('/api/projects/:id/files',auth,allow('admin','manager','staff'),uploadMw,asyncRoute(async(req,res)=>{if(!req.file)return res.status(400).json({error:'اختر ملفاً'});const kind=String(req.body.kind||'document').slice(0,30),isPublic=String(req.body.is_public||'false')==='true';const {rows}=await pool.query('INSERT INTO project_files(project_id,file_name,mime_type,size_bytes,file_data,kind,is_public,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,file_name,mime_type,size_bytes,kind,is_public,created_at',[req.params.id,req.file.originalname,req.file.mimetype,req.file.size,req.file.buffer,kind,isPublic,req.user.sub]);await audit(req,'upload','project_file',rows[0].id,{projectId:req.params.id});res.status(201).json(rows[0])}));
app.get('/api/projects/:id/files',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,file_name,mime_type,size_bytes,kind,is_public,created_at FROM project_files WHERE project_id=$1 ORDER BY created_at DESC',[req.params.id]);res.json(rows)}));
app.get('/api/project-files/:id/download',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT file_name,mime_type,file_data FROM project_files WHERE id=$1',[req.params.id]);if(!rows[0])return res.status(404).end();res.setHeader('Content-Type',rows[0].mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(rows[0].file_name)}`);res.send(rows[0].file_data)}));
app.delete('/api/project-files/:id',auth,allow('admin','manager'),asyncRoute(async(req,res)=>{await pool.query('DELETE FROM project_files WHERE id=$1',[req.params.id]);await audit(req,'delete','project_file',req.params.id);res.status(204).end()}));
app.get('/api/donations/:id/receipt',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,file_name,mime_type,size_bytes,created_at FROM donation_attachments WHERE donation_id=$1 ORDER BY created_at DESC LIMIT 1',[req.params.id]);res.json(rows[0]||null)}));
app.get('/api/donation-receipts/:id/download',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT file_name,mime_type,file_data FROM donation_attachments WHERE id=$1',[req.params.id]);if(!rows[0])return res.status(404).end();res.setHeader('Content-Type',rows[0].mime_type);res.setHeader('Content-Disposition',`attachment; filename*=UTF-8''${encodeURIComponent(rows[0].file_name)}`);res.send(rows[0].file_data)}));

app.use((err,req,res,_next)=>{console.error(`[${req.requestId}]`,err);if(res.headersSent)return;if(err instanceof z.ZodError)return res.status(400).json({error:'بيانات غير صالحة',details:err.flatten(),requestId:req.requestId});if(err?.message==='Not allowed by CORS')return res.status(403).json({error:'المصدر غير مسموح',requestId:req.requestId});if(err?.code==='23505')return res.status(409).json({error:'القيمة مستخدمة مسبقاً',requestId:req.requestId});res.status(500).json({error:err.message||'حدث خطأ داخلي',requestId:req.requestId})});
app.listen(port,()=>console.log(`BUNYAN Cloud API 7.0.0 listening on ${port}`));
