import {dirname,resolve} from 'node:path';
// Real workerd + local D1 + actual qrcode. No Cloudflare or Meta credentials.
import assert from 'node:assert/strict';
import {pbkdf2Sync,createHmac} from 'node:crypto';
import {Miniflare,createFetchMock} from 'miniflare';
const ORIGIN='https://members.shamsphone.net';
const fetchMock=createFetchMock();fetchMock.disableNetConnect();
const bundlePath=resolve(process.env.WDN_BUNDLE||'/tmp/wdn-compiled/index.js');
const mf=new Miniflare({modules:true,modulesRoot:dirname(bundlePath),scriptPath:bundlePath,
  compatibilityDate:process.env.WDN_TEST_COMPATIBILITY_DATE||'2026-09-01',compatibilityFlags:['nodejs_compat'],cf:false,
  d1Databases:{DB:'wdn-isolated-test-only'},fetchMock,
  bindings:{APP_ORIGIN:ORIGIN,WHATSAPP_MODE:'disabled',WHATSAPP_APP_SECRET:'fixture-webhook-secret-not-production'}});
let checks=0;
function check(condition,label){assert.ok(condition,label);console.log('PASS '+(++checks)+' '+label);}
async function request(path,{body,cookie='',method=body?'POST':'GET',headers={}}={}){
  const res=await mf.dispatchFetch(ORIGIN+path,{method,redirect:'manual',headers:{origin:ORIGIN,cookie,...headers},body:body?new URLSearchParams(body):undefined});
  const text=await res.text();return {res,text};
}
try{
  const db=await mf.getD1Database('DB');
  let r=await request('/membership');check(r.res.status===200,'first request membership page initializes correctly');
  await request('/staff-login');
  const salt='00112233445566778899aabbccddeeff';
  const hash=pbkdf2Sync('FixtureOnly-2026',Buffer.from(salt,'hex'),150000,32,'sha256').toString('hex');
  await db.prepare('INSERT INTO club_staff_users(username,full_name,role,password_hash,password_salt) VALUES(?,?,?,?,?)').bind('fixture-secretary','Test Only','secretary',hash,salt).run();
  r=await request('/staff-login',{body:{username:'fixture-secretary',password:'FixtureOnly-2026',next:'/club-admin'}});
  check(r.res.status===303 && !!r.res.headers.get('set-cookie'),'PBKDF2-150000 staff login works in workerd');
  const cookie=r.res.headers.get('set-cookie').split(';')[0];
  for(const path of ['/club-admin','/club-admin/content','/applications','/club-admin/backup.json'])check((await request(path,{cookie})).res.status===200,'staff access '+path);
  const join={full_name:'عضو اختبار غير حقيقي',phone:'249912000001',birth_date:'1990-01-01',address:'TEST ONLY',consent:'1'};
  r=await request('/membership',{body:join});check(r.res.status===201,'application created once');
  r=await request('/membership',{body:join});check(r.res.status===200,'duplicate returns existing request');
  check((await db.prepare('SELECT COUNT(*) c FROM applications').first()).c===1,'one application in local D1');
  const application=await db.prepare('SELECT * FROM applications').first();
  r=await request(`/applications/${application.id}/stage/approve`,{body:{},cookie});check(r.res.status===303,'approval completes');
  const member=await db.prepare('SELECT * FROM members').first();
  check(!!member?.qr_token && member.application_id===application.id,'member and token linked');
  r=await request(`/club-admin/applications/${application.id}/issue-card`,{body:{},cookie});check(r.res.status===303,'second issuance reuses card');
  check((await db.prepare('SELECT COUNT(*) c FROM members').first()).c===1,'repeated issuance never duplicates member');
  r=await request('/member-card/'+member.qr_token);check(r.res.status===200 && r.text.includes('<svg'),'actual QR SVG generated by qrcode in workerd');
  check(!r.text.includes(join.phone),'phone is not exposed on public card');
  r=await request('/verify/'+member.qr_token);check(r.res.status===200 && r.text.includes('صحيحة وسارية'),'token verification reports active membership');
  await db.prepare("UPDATE members SET status='suspended' WHERE id=?").bind(member.id).run();
  r=await request('/verify/'+member.qr_token);check(r.text.includes('غير سارية'),'suspended membership not shown active');
  check((await request('/club-admin/payments/987/status',{body:{},cookie})).res.status===403,'secretary cannot mutate finance through legacy alias');
  check((await request('/club-admin/content/news',{body:{title:'Not saved'},cookie,headers:{origin:'https://bad.invalid'}})).res.status===403,'cross-origin authenticated write rejected');
  check((await request('/club-admin/notifications/history',{cookie:'sid=invalid'})).res.status===303,'invalid legacy cookie does not expose notifications');
  // Synthetic provider receipt, never an actual WhatsApp delivery claim.
  await db.prepare("INSERT INTO club_notifications(provider_message_id,event_type,status) VALUES('fixture-message','fixture','sent')").run();
  async function receipt(status,signed=true){
    const raw=JSON.stringify({entry:[{changes:[{value:{statuses:[{id:'fixture-message',status,timestamp:String(Math.floor(Date.now()/1000))}]}}]}]});
    const signature='sha256='+createHmac('sha256','fixture-webhook-secret-not-production').update(raw).digest('hex');
    return mf.dispatchFetch(ORIGIN+'/webhooks/whatsapp',{method:'POST',headers:{'content-type':'application/json',...(signed?{'x-hub-signature-256':signature}:{})},body:raw});
  }
  check((await receipt('delivered',false)).status===403,'unsigned webhook rejected before database write');
  check((await receipt('delivered')).status===200,'signed synthetic delivery receipt accepted');
  check((await db.prepare("SELECT status FROM club_notifications WHERE provider_message_id='fixture-message'").first()).status==='delivered','receipt recorded as delivered only after valid signature');
  await receipt('read');await receipt('delivered');
  check((await db.prepare("SELECT status FROM club_notifications WHERE provider_message_id='fixture-message'").first()).status==='read','out-of-order receipt does not downgrade read');
  await request('/login');check((await db.prepare('SELECT COUNT(*) c FROM admins').first()).c===0,'no fallback administrator created');
  console.log(JSON.stringify({runtime:'workerd + local D1',compatibilityDate:process.env.WDN_TEST_COMPATIBILITY_DATE||'2026-09-01',checks,productionWrites:0,liveMessagesSent:0}));
}finally{await mf.dispose();await fetchMock.close();}
