export const CLUB='نادي ود نفيع الرياضي الثقافي الاجتماعي';
export const LOGO='/assets/wdn-logo-v42.jpg?v=49';
export const ORIGIN='https://members.shamsphone.net';
export function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const groups=[
 ['عن النادي',[['/about','نبذة عن النادي'],['/history','التاريخ'],['/identity','الرؤية والقيم'],['/board','مجلس الإدارة'],['/constitution','النظام الأساسي']]],
 ['حياة النادي',[['/activities','الأنشطة'],['/team','الفريق'],['/achievements','الإنجازات'],['/events','الفعاليات'],['/gallery','الصور'],['/sponsors','الداعمون']]]
];
function link(p,t,current){return '<a href="'+p+'"'+(p===current?' aria-current="page"':'')+'>'+t+'</a>'}
export function header(current='/'){
 const links=link('/','الرئيسية',current)+groups.map(([t,items])=>'<details class="wdn-group"><summary>'+t+'</summary><div>'+items.map(([p,l])=>link(p,l,current)).join('')+'</div></details>').join('')+link('/news','الأخبار',current)+link('/projects','المشروعات',current)+link('/contact','تواصل',current);
 const mobile=link('/','الرئيسية',current)+groups.map(([t,items])=>'<b>'+t+'</b>'+items.map(([p,l])=>link(p,l,current)).join('')).join('')+[['/news','الأخبار'],['/projects','المشروعات'],['/membership/track','متابعة الطلب'],['/membership/payment','إشعار دفع'],['/contact','تواصل'],['/staff-login','دخول المسؤولين']].map(([p,t])=>link(p,t,current)).join('');
 return '<a class="wdn-skip" href="#wdn-main">انتقل إلى المحتوى</a><header class="wdn-header"><div class="wdn-header-inner"><a href="/" class="wdn-brand"><img src="'+LOGO+'" width="48" height="48" alt="شعار نادي ود نفيع"><span><b>نادي ود نفيع</b><small>رياضة · ثقافة · مجتمع</small></span></a><nav class="wdn-desktop" aria-label="القائمة الرئيسية">'+links+'</nav><a class="wdn-join" href="/membership">طلب عضوية</a><details class="wdn-mobile"><summary>القائمة</summary><nav aria-label="قائمة الهاتف">'+mobile+'</nav></details></div></header>';
}
export function footer(){return '<footer class="wdn-footer"><div><b>'+CLUB+'</b><p>تأسس عام 1964 · ود نفيع، المناقل</p></div><nav aria-label="روابط الخدمات"><a href="/membership">طلب عضوية</a><a href="/membership/track">متابعة الطلب</a><a href="/membership/payment">إشعار دفع</a><a href="/constitution">النظام الأساسي</a><a href="/staff-login">دخول المسؤولين</a><a href="/contact">تواصل معنا</a></nav><small>© '+new Date().getFullYear()+' نادي ود نفيع</small></footer>'}
export const sharedCss=[
 '.wdn-header,.wdn-header *,.wdn-footer,.wdn-footer *{box-sizing:border-box}',
 'header.wdn-header{position:relative;inset:auto;z-index:50;background:#fff;color:#132b50;border:0;border-bottom:1px solid #dce3ed;padding:0;display:block;backdrop-filter:none}',
 '.wdn-header-inner{max-width:1240px;margin:auto;min-height:88px;display:flex;align-items:center;gap:22px;padding:16px 28px}',
 '.wdn-header .wdn-brand{display:flex;align-items:center;gap:12px;flex:0 0 auto;text-decoration:none;color:#132b50}.wdn-brand img{width:48px;height:48px;object-fit:contain;border-radius:10px;background:#fff;padding:0}.wdn-brand b{display:block;font-size:20px;color:#122b52;line-height:1.5;white-space:nowrap}.wdn-brand small{display:block;font-size:11px;color:#627086;white-space:nowrap}',
 '.wdn-header nav.wdn-desktop{position:static;display:flex;align-items:center;justify-content:center;gap:4px;flex:1;background:none;border:0;padding:0;flex-direction:row;flex-wrap:nowrap}',
 '.wdn-header nav a,.wdn-header summary{display:block;color:#243d5b;font:inherit;font-size:14px;font-weight:600;padding:10px 9px;border-radius:8px;text-decoration:none;white-space:nowrap;cursor:pointer;min-height:44px}.wdn-header nav a:hover,.wdn-header summary:hover,.wdn-header [aria-current=page]{background:#edf2f8;color:#123d78}',
 '.wdn-group{position:relative}.wdn-group summary{list-style:none}.wdn-group summary:after{content:"⌄";margin-inline-start:7px}.wdn-group summary::-webkit-details-marker{display:none}.wdn-group>div{position:absolute;top:100%;inset-inline-start:0;min-width:205px;padding:8px;background:#fff;border:1px solid #dce3ed;border-radius:12px;box-shadow:0 12px 30px #132b501a}',
 '.wdn-header a.wdn-join{display:block;background:#e6b73e;color:#142c50;padding:11px 18px;border-radius:9px;font-size:14px;font-weight:800;text-decoration:none;white-space:nowrap;min-height:44px}.wdn-header .wdn-mobile{display:none}.wdn-skip{position:fixed;top:-100px;right:12px;z-index:100;background:#fff;color:#122b52;padding:12px}.wdn-skip:focus{top:8px}:focus-visible{outline:3px solid #b58113;outline-offset:4px}',
 'footer.wdn-footer{margin-top:64px;background:#102746;color:#e8eef5;padding:34px max(24px,calc((100% - 1184px)/2));display:grid;grid-template-columns:1fr 1fr;gap:24px;text-align:right}.wdn-footer>div{display:block!important}.wdn-footer b{font-size:17px}.wdn-footer p{font-size:13px;color:#bcc9db;margin:7px 0}.wdn-footer nav{display:flex;gap:6px 20px;flex-wrap:wrap;position:static;background:none;padding:0;border:0}.wdn-footer a{color:#e8eef5;text-decoration:none;font-size:13px;padding:8px 0;min-height:44px}.wdn-footer small{grid-column:1/-1;padding-top:18px;border-top:1px solid #ffffff24;color:#bcc9db}',
 '@media(max-width:1080px){.wdn-header-inner{gap:12px;padding:12px 18px;min-height:76px}.wdn-header nav.wdn-desktop{display:none}.wdn-header .wdn-mobile{display:block;position:static}.wdn-header .wdn-mobile>summary{background:#edf2f8;padding:11px 13px;list-style:none}.wdn-mobile>summary::-webkit-details-marker{display:none}.wdn-header a.wdn-join{margin-inline-start:auto}.wdn-header .wdn-mobile nav{display:grid;position:absolute;inset-inline:12px;top:calc(100% + 6px);max-height:72vh;overflow:auto;background:#fff;border:1px solid #dce3ed;border-radius:12px;box-shadow:0 14px 35px #122b5220;padding:14px;gap:2px;grid-template-columns:1fr 1fr}.wdn-mobile nav b{grid-column:1/-1;color:#63758b;border-top:1px solid #e4e9f1;padding:12px 9px 4px;font-size:12px}}',
 '@media(max-width:520px){.wdn-header-inner{padding:10px 12px;gap:8px}.wdn-brand img{width:36px;height:36px}.wdn-brand b{font-size:16px}.wdn-brand small{font-size:10px}.wdn-header .wdn-brand{gap:7px}.wdn-header a.wdn-join{padding:11px 10px;font-size:12px}.wdn-header .wdn-mobile>summary{font-size:12px;padding:11px 9px}.wdn-footer{grid-template-columns:1fr!important}}',
 '@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto!important}*,*:before,*:after{animation:none!important;transition:none!important}}@media print{.wdn-header,.wdn-footer,.wdn-skip{display:none!important}}'
].join('\n');
export const siteCss=[
 '*{box-sizing:border-box}body{margin:0;background:#f7f9fc;color:#172e4c;font-family:system-ui,-apple-system,"Segoe UI",Tahoma,Arial;line-height:1.8}a{color:#17487f}img{max-width:100%}main{min-height:50vh}h1,h2,h3,p{overflow-wrap:anywhere}h1,h2,h3{line-height:1.4}h2{font-size:clamp(23px,3vw,32px);margin:0 0 14px}h3{font-size:20px;margin:6px 0 12px}p{margin:8px 0 16px;color:#55677d}',
 '.wdn-wrap{width:min(1184px,calc(100% - 48px));margin:40px auto}.wdn-hero{background:#102d56;color:#fff}.wdn-hero-inner{width:min(1184px,calc(100% - 48px));margin:auto;display:grid;grid-template-columns:1.4fr 1fr;gap:64px;align-items:center;padding:64px 0}.wdn-eyebrow{display:inline-block;color:#eed28c;font-size:13px;font-weight:700}.wdn-hero h1{font-size:clamp(36px,5vw,64px);line-height:1.25;margin:16px 0}.wdn-hero h1 span{display:block;color:#edd396}.wdn-hero p{color:#d4deeb;font-size:17px;max-width:640px}.wdn-hero-art{display:grid;place-items:center;padding:26px}.wdn-hero-art img{width:220px;height:220px;object-fit:contain;background:white;padding:15px;border-radius:28px;box-shadow:24px 24px 0 #ffffff08,-20px -20px 0 #ffffff05}.wdn-hero-art small{margin-top:32px;color:#eed28c}',
 '.wdn-actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:24px}.wdn-button{display:inline-flex;align-items:center;justify-content:center;min-height:46px;padding:10px 20px;background:#e6b73e;color:#132b50;border:1px solid transparent;border-radius:9px;text-decoration:none;font:inherit;font-weight:750;cursor:pointer}.wdn-button.secondary{background:transparent;color:inherit;border-color:#6b829f}',
 '.wdn-services{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));border:1px solid #dce3ed;border-radius:16px;overflow:hidden;background:#fff;margin-top:28px}.wdn-service{padding:24px;text-decoration:none;border-inline-end:1px solid #e1e7ef;color:#18375d}.wdn-service:last-child{border:0}.wdn-service small{display:block;color:#987019;font-size:12px}.wdn-service strong{display:block;font-size:19px;margin:4px 0}.wdn-service span{font-size:13px;color:#65758b}.wdn-service:hover{background:#f0f5fb}',
 '.wdn-section{margin-block:52px}.wdn-section-head{display:flex;align-items:center;justify-content:space-between;gap:20px;margin-bottom:18px}.wdn-section-head h2{margin:0}.wdn-section-head a{font-size:14px;text-decoration:none;white-space:nowrap}.wdn-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.wdn-grid.two{grid-template-columns:repeat(2,minmax(0,1fr))}.wdn-card{padding:26px;border:1px solid #dce3ed;background:#fff;border-radius:14px;min-width:0}.wdn-card p{font-size:15px;white-space:pre-line}.wdn-card small{color:#697b90}.wdn-card img{display:block;width:100%;aspect-ratio:16/10;object-fit:cover;border-radius:9px;margin-bottom:18px}.wdn-label{font-size:12px;color:#8b651a;font-weight:700}.wdn-empty{padding:30px;border:1px dashed #c8d3e0;border-radius:14px;background:#fff;text-align:center;color:#52677f}.wdn-empty p{margin:0}',
 '.wdn-band{background:#eaf0f7;border-radius:16px;padding:32px;display:flex;justify-content:space-between;gap:24px;align-items:center}.wdn-band p{margin:0}.wdn-band .wdn-button{flex-shrink:0}.wdn-pagehead{background:#eaf0f7;border-bottom:1px solid #dce3ed;padding:42px max(24px,calc((100% - 1184px)/2))}.wdn-pagehead h1{font-size:clamp(30px,4vw,44px);margin:8px 0 12px}.wdn-pagehead p{max-width:780px;margin:0}.wdn-breadcrumb{font-size:13px;color:#6a798c}.wdn-breadcrumb a{text-decoration:none}.wdn-reading{max-width:840px}.wdn-note{background:#fff7e7;border:1px solid #ead6a8;border-radius:10px;padding:14px 18px;font-size:14px}.wdn-contact{display:block;color:inherit;text-decoration:none}.wdn-contact b{font-size:21px}.wdn-contact span{display:block;color:#586d85}',
 '@media(max-width:760px){.wdn-hero-inner{grid-template-columns:1fr;gap:24px;padding:36px 0}.wdn-hero-art{display:none}.wdn-hero h1{font-size:40px}.wdn-wrap,.wdn-hero-inner{width:calc(100% - 32px)}.wdn-grid,.wdn-grid.two{grid-template-columns:1fr}.wdn-services{grid-template-columns:1fr}.wdn-service{border-inline-end:0;border-bottom:1px solid #e1e7ef;padding:18px 22px}.wdn-band{display:block;padding:24px}.wdn-band .wdn-button{margin-top:18px}.wdn-section{margin-block:36px}.wdn-pagehead{padding:28px 18px}.wdn-section-head{align-items:start}.wdn-card{padding:22px}}'
].join('\n');
export function page(title,description,body,path='/',status=200){
 return new Response('<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#102746"><meta name="description" content="'+esc(description)+'"><meta property="og:title" content="'+esc(title)+' · نادي ود نفيع"><meta property="og:description" content="'+esc(description)+'"><meta property="og:image" content="'+ORIGIN+LOGO+'"><meta property="og:url" content="'+ORIGIN+path+'"><link rel="canonical" href="'+ORIGIN+path+'"><title>'+esc(title)+' · نادي ود نفيع</title><style>'+siteCss+sharedCss+'</style></head><body>'+header(path)+'<main id="wdn-main" tabindex="-1">'+body+'</main>'+footer()+'</body></html>',{status,headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin','x-wadnofei-ui':'v78-organized-site'}});
}
